Repository sopel-irc/sopel, pull requests merged in 2018-05, with the labels that each got.

#1062 coretasks: remove sticky modifier from account capability requests
  sopel/coretasks.py
Labels: Tweak

#1321 Add missing docstring to 'set_channel_value' function
  sopel/db.py
Labels: Documentation, Tweak

#989 [db] Use IF NOT EXISTS when creating tables
  sopel/db.py
Labels: Tweak

#1033 Support geoip lookup for IPv6 and nicknames
  sopel/modules/ip.py
Labels: Feature
