Repository sopel-irc/sopel, pull requests merged in 2018-03, with the labels that each got.

#1258 Fix tests
  .travis.yml
  conftest.py
  sopel/modules/ip.py
Labels: Bug, Tests

#1264 Comment housekeeping
  contrib/sopel.cfg
  sopel/coretasks.py
  sopel/formatting.py
  sopel/modules/calc.py
  sopel/modules/currency.py
  sopel/modules/find.py
  sopel/modules/lmgtfy.py
  sopel/modules/meetbot.py
  sopel/modules/pronouns.py
  sopel/modules/wikipedia.py
Labels: Documentation, Low Priority, Tweak

#1215 Work around websites in the Gawker family with their HTTP title gore
  sopel/modules/url.py
Labels: Bug, Tweak

#1257 Replace deprecated gist API in help
  sopel/modules/help.py
Labels: Bug, High Priority

#1263 Fix IPython requirement
  dev-requirements.txt
  requirements.txt
Labels: Bug

#1185 Add correct timezone time in the .in sub-module of the remind module
  sopel/modules/remind.py
Labels: Tweak

#1277 [help] use help_prefix instead of assuming "."
  sopel/modules/help.py
Labels: Tweak

#1265 fix .g giving broken result
  sopel/modules/search.py
Labels: Bug

#1270 [wikipedia] Return friendly error on missing pages
  sopel/modules/wikipedia.py
Labels: Bug, Tweak

#1261 currency: limit precision to two decimal places
  sopel/modules/currency.py
Labels: Tweak

#1271 Clean up badges in README
  README.rst
Labels: Documentation, Tweak

#1262 Quote Wikipedia query for use in API call
  sopel/modules/wikipedia.py
Labels: Bug, Low Priority, Tweak

#1249 TLS root cert fixes
  sopel/config/core_section.py
Labels: Medium Priority, Tweak

#1275 Make __future__ imports consistent
  pytest_run.py
  setup.py
  sopel.py
  sopel/__init__.py
  sopel/config/types.py
  sopel/coretasks.py
  sopel/formatting.py
  sopel/modules/countdown.py
  sopel/modules/dice.py
  sopel/modules/ipython.py
  sopel/modules/lmgtfy.py
  sopel/modules/meetbot.py
  sopel/modules/movie.py
  sopel/modules/spellcheck.py
  sopel/modules/translate.py
  sopel/modules/unicode_info.py
  sopel/modules/units.py
  sopel/modules/wikipedia.py
  test/test_db.py
  test/test_irc.py
Labels: Low Priority, Tweak

#987 [reload] Prevent reloading nonexistent module
  sopel/modules/reload.py
Labels: Tweak

#1207 logger: format arguments for logging channel messages
  sopel/logger.py
Labels: Tweak

#1267 Allow any 2.x version of requests
  requirements.txt
Labels: Tweak

#1268 Require PRAW >= 4.0.0
  requirements.txt
Labels: Tweak

#1278 Start failing builds on style checks
  .travis.yml
  setup.py
  sopel/__init__.py
  sopel/bot.py
  sopel/config/__init__.py
  sopel/config/core_section.py
  sopel/config/types.py
  sopel/coretasks.py
  sopel/db.py
  sopel/irc.py
  sopel/loader.py
  sopel/logger.py
  sopel/modules/clock.py
  sopel/modules/countdown.py
  sopel/modules/currency.py
  sopel/modules/help.py
  sopel/modules/isup.py
  sopel/modules/meetbot.py
  sopel/modules/pronouns.py
  sopel/modules/reddit.py
  sopel/modules/remind.py
  sopel/modules/safety.py
  sopel/modules/search.py
  sopel/modules/translate.py
  sopel/modules/unicode_info.py
  sopel/modules/units.py
  sopel/modules/url.py
  sopel/modules/wiktionary.py
  sopel/run_script.py
  sopel/tools/__init__.py
  sopel/tools/jobs.py
  sopel/tools/target.py
  sopel/tools/time.py
  sopel/web.py
  test/test_irc.py
Labels: Tests, Tweak

#1280 [config.types] Filter ListAttribute empty values
  sopel/config/types.py
Labels: Bug, Tweak

#1286 [calc] Switch to Sopel's own tumbolia instance
  sopel/modules/calc.py
Labels: Feature, Tests, Tweak

#1282 Switch wikipedia module from sopel.web to requests
  sopel/modules/wikipedia.py
Labels: Tweak

#1285 [calc] Switch from sopel.web to requests
  sopel/modules/calc.py
Labels: Tweak

#1284 tell: Catch py2 IOError in setup()
  sopel/modules/tell.py
Labels: Tweak

#1288 Fixed space stripping in pronouns.py
  sopel/modules/pronouns.py
Labels: Tweak

#1287 Pytest setup shenanigans
  sopel/module.py
  sopel/modules/ip.py
  sopel/modules/url.py
  sopel/test_tools.py
Labels: Tests, Tweak

#1184 add physical limit to temperature conversion (units module)
  sopel/modules/units.py
Labels: Tweak

#1292 wikipedia: Prevent triggering on other Sopel bots
  sopel/modules/wikipedia.py
Labels: Bug

#1289 search: Fix .suggest with Google suggestion API
  sopel/modules/search.py
Labels: Bug, Tweak
