Repository sopel-irc/sopel, pull requests merged in 2018-04, with the labels that each got.

#1296 module: only inject test functions if testing
  sopel/module.py
Labels: Bug, High Priority, Tests

#1297 Prune tests from release distribution
  MANIFEST.in
Labels: Build, Tweak

#1307 Revert "Prune tests from release distribution"
  MANIFEST.in
Labels: Build

#1310 Fix IPython requirement for real
  requirements.txt
Labels: Bug, Medium Priority

#1312 reddit: Cross-compatibility for praw
  requirements.txt
  sopel/modules/reddit.py
Labels: Tweak

#1299 Additional config tests
  sopel/config/types.py
  test/test_config.py
Labels: Tests

#1293 Update to testing process
  .coveragerc
  .travis.yml
  dev-requirements.txt
  pytest.ini
  pytest_run.py
  setup.py
Labels: Tests
