Repository sopel-irc/sopel, pull requests merged in 2018-06, with the labels that each got.

#1217 Add option to authenticate using userserv
  sopel/config/core_section.py
  sopel/coretasks.py
Labels: Feature

#1241 core, loader, version: Fix intent handling and CTCP replies
  sopel/bot.py
  sopel/loader.py
  sopel/modules/version.py
Labels: Bug, Tweak

#1168 Add command for checking https sites with untrusted cert.
  sopel/modules/isup.py
Labels: Feature, Tweak

#1300 formatting: add italics
  sopel/formatting.py
  test/test_formatting.py
Labels: Feature, Tests

#1327 web: mark deprecated methods for coverage exclude
  sopel/web.py
Labels: Tests, Tweak

#1052 Add nick alias config option for $nick and $nickname in @rule regex
  sopel/config/core_section.py
  sopel/loader.py
Labels: Feature

#1344 Nickname commands fix & testing
  sopel/loader.py
  sopel/module.py
  sopel/tools/__init__.py
  test/test_commands.py
  test/test_module.py
Labels: Bug, High Priority, Tests

#1347 search: apply Unicode fix for unquote() from wikipedia
  sopel/modules/search.py
Labels: Bug, Tests
