Repository sopel-irc/sopel, pull requests merged in 2018-12, with the labels that each got.

#1375 reddit: Link to user page with HTTPS
  sopel/modules/reddit.py
Labels: Tweak

#1376 safety: retrieve MalwareDomains list over HTTPS
  sopel/modules/safety.py
Labels: Tweak

#1377 weather: convert WOEID lookup to HTTPS too
  sopel/modules/weather.py
Labels: Tweak

#1397 add support for old.reddit.com links
  sopel/modules/reddit.py
Labels: Low Priority, Tweak

#1368 formatting: add hex color support
  sopel/formatting.py
  test/test_formatting.py
Labels: Feature

#1379 formatting: add reverse-color support
  sopel/formatting.py
  test/test_formatting.py
Labels: Feature

#1380 url: Say something on .title command failure
  sopel/modules/url.py
Labels: Tweak

#1386 dice: invalid dice rolls now gives a more friendly error
  sopel/modules/dice.py
Labels: Tweak

#1392 weather: Bundle of small tweaks
  sopel/modules/weather.py
Labels: Tweak

#1381 fix: ctrl-c now runs shutdown routines
  sopel/__init__.py
Labels: Bug, Low Priority

#1388 irc: sopel now runs shutdown routines on connection error
  sopel/irc.py
Labels: Bug, Medium Priority

#1405 wiktionary: fix inability to look up affixes
  sopel/modules/wiktionary.py
Labels: Bug

#1406 tld: add argument check
  sopel/modules/tld.py
Labels: Bug

#1409 wiktionary: fix failed lookup for certain words
  sopel/modules/wiktionary.py
Labels: Bug

#1410 xkcd: Change search engine from Duckduckgo to Bing
  sopel/modules/xkcd.py
Labels: Bug

#1421 dice: strip whitespace from choices
  sopel/modules/dice.py
Labels: Bug

#1428 test: add coverage_html_report dir to gitignore
  .gitignore
Labels: Tweak
