Repository sopel-irc/sopel, pull requests merged in 2019-11, with the labels that each got.

#1727 module: fix `__all__` nonsense & docs for `event`
  sopel/module.py
Labels: Bugfix, Documentation, Tweak

#1679 dice, choose: extract `.choose` command into own module
  sopel/modules/choose.py
  sopel/modules/dice.py
Labels: Low Priority, Tweak

#1680 doc: more about nick, user, and name
  docs/source/configuration.rst
Labels: Documentation, Low Priority

#1681 tools.web: add `unquote()` function
  sopel/modules/calc.py
  sopel/modules/search.py
  sopel/modules/wikipedia.py
  sopel/tools/web.py
  test/tools/test_tools_web.py
Labels: Feature, Low Priority

#1707 tools.time: fully utilize pytz to validate timezones
  sopel/tools/time.py
Labels: Low Priority, Tweak

#1736 remind: fix default_timezone in .at command when tz not specified
  sopel/modules/remind.py
Labels: Bugfix, Medium Priority

#1737 coretasks: fixing bot truncating users with same mode
  sopel/coretasks.py
Labels: Bugfix, High Priority

#1729 db: add pool_recycle to db creation
  sopel/db.py
Labels: Tweak

#1709 loader: don't add defaults to non-triggerables in clean_callable
  sopel/loader.py
  test/test_loader.py
Labels: Tweak

#1717 modules: Tweak some old examples to use new features
  sopel/modules/admin.py
  sopel/modules/dice.py
  sopel/modules/invite.py
  sopel/modules/lmgtfy.py
  sopel/modules/meetbot.py
  sopel/modules/unicode_info.py
Labels: Low Priority, Tweak

#1719 config.types: doc ALL the things!
  sopel/config/types.py
Labels: Documentation

#1696 clock: remove obsolete config options
  sopel/modules/clock.py
Labels: Low Priority, Tweak

#1702 instagram: catch parse errors
  sopel/modules/instagram.py
Labels: Bugfix, Tweak

#1706 plugins: remove nonsense uses of core.verify_ssl
  sopel/modules/find_updates.py
  sopel/modules/meetbot.py
  sopel/modules/translate.py
  sopel/modules/url.py
  sopel/modules/xkcd.py
Labels: Tweak

#1713 search: don't unquote DDG result
  sopel/modules/search.py
Labels: Bugfix

#1715 remind: use reply in case of error fix #1644
  sopel/modules/remind.py
Labels: Low Priority, Tweak

#1748 plugins: add licence and author
  sopel/plugins/__init__.py
  sopel/plugins/exceptions.py
  sopel/plugins/handlers.py
Labels: Low Priority, Tweak

#1694 tell: use config to send reminders as private messages
  sopel/modules/tell.py
  test/modules/test_modules_tell.py
Labels: Feature, Low Priority

#1699 remind, tell: Use config name in fake `.db` files
  sopel/modules/remind.py
  sopel/modules/tell.py
  test/modules/test_modules_remind.py
Labels: Documentation, Tweak

#1730 cleanup: remove things marked for version 7.0
  sopel/bot.py
  sopel/loader.py
  sopel/test_tools.py
  sopel/web.py
Labels: Medium Priority, Tweak

#1741 qa: quick fixes via LGTM
  sopel/config/__init__.py
  sopel/config/types.py
  sopel/irc/backends.py
  sopel/irc/utils.py
  sopel/modules/adminchannel.py
  sopel/modules/clock.py
  sopel/modules/help.py
  sopel/modules/safety.py
Labels: Bugfix, Medium Priority

#1718 cli.run: print version info at startup
  sopel/cli/run.py
Labels: Low Priority, Tweak

#1750 config: fix documentation errors
  docs/source/configuration.rst
  sopel/config/__init__.py
  sopel/config/types.py
Labels: Documentation, High Priority

#1733 module: add `require account` feature
  sopel/module.py
  test/test_module.py
Labels: Feature, Medium Priority

#1700 help: add `reply_method` option
  sopel/modules/help.py
Labels: Feature

#1701 module, bot: add `output_prefix` decorator & feature
  sopel/bot.py
  sopel/loader.py
  sopel/module.py
  test/test_module.py
Labels: Feature

#1754 qa: fix additional LGTM alerts
  contrib/rpm/makerpm.py
  sopel/cli/config.py
  sopel/cli/plugins.py
  sopel/cli/utils.py
  sopel/config/types.py
  sopel/irc/backends.py
  sopel/module.py
  sopel/modules/admin.py
  sopel/modules/help.py
  sopel/modules/isup.py
  sopel/modules/remind.py
  sopel/plugins/handlers.py
  sopel/tools/__init__.py
Labels: Tweak

#1710 calc: extract .py command to its own file
  sopel/modules/calc.py
  sopel/modules/py.py
Labels: Tweak

#1716 test: URL callbacks (register, search, unregister)
  test/test_bot.py
Labels: Low Priority, Tests

#1711 py: use output_prefix
  sopel/modules/py.py
Labels: Tweak

#1712 py: configurable endpoint
  sopel/modules/py.py
Labels: Feature

#1720 reddit: add comment handling
  sopel/modules/reddit.py
Labels: Feature

#1734 reddit: media details (+ refactoring)
  sopel/modules/reddit.py
Labels: Feature, Medium Priority

#1721 find: optimizations
  sopel/modules/find.py
Labels: Low Priority, Tweak

#1725 plugins: unblock background triggers
  sopel/modules/seen.py
  sopel/modules/tell.py
  sopel/modules/translate.py
Labels: Tweak

#1728 bot: fix race-condition in dispatch
  sopel/bot.py
  sopel/module.py
Labels: Bugfix, Medium Priority

#1731 test: botfactory, UserFactory, and IRCFactory
  .gitignore
  docs/source/index.rst
  docs/source/tests.rst
  setup.py
  sopel/test_tools.py
  sopel/tests/__init__.py
  sopel/tests/factories.py
  sopel/tests/mocks.py
  sopel/tests/pytest_plugin.py
  test/irc/test_irc_abstract_backends.py
  test/test_bot.py
  test/test_coretasks.py
  test/test_irc.py
  test/test_loader.py
Labels: Feature, Tests

#1732 bot: keep track of trigger processing threads
  sopel/bot.py
Labels: Medium Priority, Tweak

#1673 db: allow requesting a default if key not found
  sopel/db.py
  sopel/modules/adminchannel.py
  test/test_db.py
Labels: Tweak

#1759 bot: fix bug in blocked user detection
  sopel/bot.py
Labels: Bugfix, High Priority

#1722 reddit: handle subreddits, and `u/` & `r/` references
  sopel/modules/reddit.py
Labels: Feature, Low Priority

#1742 cli: replace 'module' by 'plugin'
  sopel/cli/run.py
  sopel/cli/utils.py
  test/cli/test_cli_run.py
Labels: Low Priority, Tweak

#1743 bot, config: s/module/plugin/ (where appropriate)
  sopel/bot.py
  sopel/config/__init__.py
  sopel/config/core_section.py
Labels: High Priority, Tweak

#1747 plugins: add ~/.sopel/plugins folder
  sopel/plugins/__init__.py
Labels: Low Priority, Tweak

#1739 cli: Fix plugin config duplicate y/n prompt
  sopel/cli/utils.py
Labels: Bugfix, Low Priority

#1740 bot: Fix rule callable unload message argument error
  sopel/bot.py
Labels: Bugfix, High Priority

#1749 core: do not send TOPIC on join
  sopel/coretasks.py
Labels: Low Priority, Tweak
