Repository sopel-irc/sopel, pull requests merged in 2019-09, with the labels that each got.

#1632 module: fix decorator multiple-use inconsistency
  sopel/bot.py
  sopel/module.py
  test/test_module.py
Labels: Tweak

#1629 currency: switched crypto api and combined rates to allow cross-lookup
  sopel/modules/currency.py
Labels: Feature, Medium Priority, Tweak

#1686 test: fix py2 inconsistency with regex ID
  test/test_module.py
Labels: Bugfix, High Priority

#1598 cli: add --config-dir common option
  sopel/cli/config.py
  sopel/cli/run.py
  sopel/cli/utils.py
  test/cli/test_cli_run.py
  test/cli/test_cli_utils.py
Labels: Feature, Low Priority

#1628 config: split ListAttribute values on newlines
  docs/source/configuration.rst
  sopel/config/types.py
  test/test_config.py
Labels: Feature, Tweak

#1556 admin: add unset command
  sopel/config/types.py
  sopel/modules/admin.py
Labels: Bugfix, Feature

#1592 clock: improve timezone guessing and refactor time-related utility
  sopel/modules/clock.py
  sopel/tools/time.py
Labels: Bugfix, Low Priority

#1633 version: fixing version formatting
  sopel/modules/version.py
Labels: Low Priority, Tweak

#1693 loader: default rule for events
  sopel/coretasks.py
  sopel/loader.py
  sopel/modules/admin.py
  sopel/modules/find_updates.py
  test/test_loader.py
Labels: Tweak

#1651 help: add pastebin.ubuntu.com as help pastebin provider
  sopel/modules/help.py
Labels: Feature, Low Priority, Tweak

#1661 seen: Improve readability of information
  sopel/modules/seen.py
Labels: Low Priority, Tweak

#1663 coretasks: update away status based on values returned from WHO call
  sopel/coretasks.py
Labels: Bug, Medium Priority

#1664 coretasks: Periodically send WHO to keep user information up-to-date
  sopel/coretasks.py
  sopel/tools/target.py
Labels: Feature, Medium Priority
