Repository sopel-irc/sopel, pull requests merged in 2019-08, with the labels that each got.

#1676 dev-requirements: cap flake8-future-import version
  dev-requirements.txt
Labels: Build, High Priority, Tests

#1668 doc: fix misuse of py:module replaced by py:currentmodule
  docs/source/configuration.rst
Labels: Bugfix, Documentation

#1627 currency: Fixed try/except fall-through
  sopel/modules/currency.py
Labels: Bugfix

#1677 etymology: handle empty argument
  sopel/modules/etymology.py
Labels: Bugfix, Low Priority

#1685 bot: replace deprecated memory.contains call
  sopel/bot.py
Labels: Low Priority, Tweak

#1621 db: add methods for values associated with a plugin
  sopel/db.py
  test/test_db.py
Labels: Feature, Medium Priority
