Repository sopel-irc/sopel, pull requests merged in 2019-02, with the labels that each got.

#1442 wiktionary: fix query logic
  sopel/modules/wiktionary.py
Labels: Tweak

#1467 Update supported IPython versions again
  requirements.txt
Labels: Build, Tweak

#1468 Get specific about dnspython requirement
  requirements.txt
Labels: Build, Tweak

#1469 NEWS: Create and enforce format spec
  NEWS
  NEWS.spec.md
Labels: Documentation, High Priority

#1329 Create .codeclimate.yml
  .codeclimate.yml
Labels: Build, Tests

#1404 config: don't assume ~/.sopel as dotdir
  sopel/config/__init__.py
Labels: Tweak

#1425 dice: clean up the dice "choose" command output (fix #1420)
  sopel/modules/dice.py
Labels: Tweak

#1474 etymology: fix py3.3 compatibility
  .travis.yml
  dev-requirements.txt
  sopel/modules/etymology.py
Labels: Bugfix, Tests

#1475 calc: Make emoji spam possible (support Unicode characters)
  sopel/modules/calc.py
Labels: Bugfix

#1476 Add docstrings for privilege levels
  sopel/module.py
Labels: Documentation, Tweak

#1480 etymology: quote URL parameters
  sopel/modules/etymology.py
Labels: Bugfix

#1481 search: quote URL parameters
  sopel/modules/search.py
Labels: Bugfix

#1487 use platform to check OS name instead of try, except
  sopel/run_script.py
Labels: Tweak

#1483 instagram: remove `u` prefix (and other cleanups)
  sopel/modules/instagram.py
Labels: Tweak

#1472 sopel.cli.utils
  setup.py
  sopel/cli/__init__.py
  sopel/cli/utils.py
  sopel/config/__init__.py
  sopel/run_script.py
  test/cli/test_cli_utils.py
  test/test_run_script.py
Labels: Feature
