Repository sopel-irc/sopel, pull requests merged in 2019-07, with the labels that each got.

#1585 plugins: load plugins from setuptools entry points
  sopel/plugins/__init__.py
  sopel/plugins/handlers.py
  test/test_plugins.py
Labels: Feature, Medium Priority

#1526 db: add methods to delete a channel or nick's key from database
  sopel/db.py
  test/test_db.py
Labels: Feature, Low Priority

#1652 db: fix unicode on mysql
  sopel/db.py
Labels: Bugfix, High Priority

#1560 tools: Add formatter for timedeltas
  sopel/tools/time.py
  test/test_tools.py
Labels: Feature, Low Priority

#1610 bot: dispatch simplification and minor optimization
  sopel/bot.py
Labels: Medium Priority, Tweak

#1582 core: add `__all__` statements in sopel fix #765
  docs/source/bot.rst
  sopel/__init__.py
  sopel/bot.py
  sopel/config/__init__.py
  sopel/formatting.py
  sopel/irc.py
  sopel/module.py
  sopel/test_tools.py
  sopel/trigger.py
  sopel/web.py
Labels: Documentation, Low Priority, Tweak

#1566 First pass of docstring additions.
  sopel/bot.py
Labels: Documentation, Medium Priority

#1646 doc: document Sopel configuration
  dev-requirements.txt
  docs/source/cli.rst
  docs/source/conf.py
  docs/source/config.rst
  docs/source/configuration.rst
  docs/source/index.rst
  docs/source/package.rst
  docs/source/run.rst
  docs/willie.man
  sopel/cli/run.py
  sopel/cli/utils.py
  sopel/config/__init__.py
  sopel/config/core_section.py
  sopel/config/types.py
Labels: Documentation, Low Priority

#1590 remind: add support for date in .at command
  sopel/modules/remind.py
  test/modules/test_modules_remind.py
Labels: Feature, Medium Priority

#1609 isup: minor cleanup with tests
  sopel/modules/isup.py
  test/modules/test_modules_isup.py
Labels: Low Priority, Tweak

#1597 bot: new setup sequence
  sopel/bot.py
  sopel/cli/run.py
  test/test_bot.py
Labels: High Priority, Tweak

#1588 cli: sopel-plugins (basic version)
  docs/source/cli.rst
  setup.py
  sopel/cli/plugins.py
  sopel/cli/utils.py
  sopel/plugins/handlers.py
  test/cli/test_cli_utils.py
  test/plugins/test_plugins_handlers.py
Labels: Feature

#1613 tools: add optional arguments to deprecated, and deprecate Ddict
  sopel/modules/meetbot.py
  sopel/tools/__init__.py
Labels: Low Priority, Tweak

#1620 reddit: spoiler update
  sopel/modules/reddit.py
Labels: Feature

#1616 Transition `web` -> `tools.web`
  .coveragerc
  sopel/cli/run.py
  sopel/coretasks.py
  sopel/modules/etymology.py
  sopel/modules/lmgtfy.py
  sopel/modules/meetbot.py
  sopel/modules/reddit.py
  sopel/modules/search.py
  sopel/modules/tld.py
  sopel/modules/translate.py
  sopel/modules/url.py
  sopel/modules/wiktionary.py
  sopel/tools/web.py
  sopel/web.py
  test/tools/test_tools_web.py
Labels: Documentation, Medium Priority, Tweak

#1670 web: fix `__all__` lists & aliases to new package
  sopel/web.py
Labels: Medium Priority, Tweak

#1624 url: minor bug fixes
  sopel/modules/url.py
Labels: Tweak
