Repository sopel-irc/sopel, pull requests merged in 2019-04, with the labels that each got.

#1529 fix: regression in testing individual modules
  sopel/modules/ipython.py
  sopel/test_tools.py
Labels: Bugfix, Tests

#1520 admin: Catch set commands without arguments
  sopel/modules/admin.py
Labels: Bugfix, Low Priority

#1164 spellcheck: complete rewrite
  .travis.yml
  contrib/rpm/sopel.spec.in
  requirements.txt
  sopel/modules/spellcheck.py
Labels: Feature

#1538 fix _store() so it accepts any named arguments
  sopel/test_tools.py
Labels: Bugfix, Tests

#1537 core: add `bot.hostmask` getter
  sopel/bot.py
Labels: Feature

#1470 irc/bot: implement echo-message
  sopel/bot.py
  sopel/coretasks.py
  sopel/irc.py
  sopel/loader.py
  sopel/module.py
  sopel/modules/find.py
  test/test_module.py
Labels: Feature

#1544 coretasks: fix malformed MODE command in startup()
  sopel/coretasks.py
Labels: Bugfix

#1521 dev: add a Makefile to the project and use setup.cfg to configure flake8
  Makefile
  checkstyle.sh
  dev-requirements.txt
  setup.cfg
Labels: Low Priority, Tweak

#1235 Support disabling modules/commands per channel
  sopel/bot.py
  sopel/config/__init__.py
Labels: Documentation, Feature

#1534 core: fix broken interrupt handling (6.6.x)
  sopel/__init__.py
  sopel/irc.py
Labels: Bugfix

#1516 Replace manual color codes with sopel.formatting
  sopel/modules/meetbot.py
  sopel/modules/reddit.py
Labels: Tweak

#1549 admin: .mode compliance with IRC specs
  sopel/modules/admin.py
Labels: Bugfix

#1552 core: limit maximum flood penalty
  sopel/bot.py
Labels: Bugfix

#1558 core: fix interrupt during connection phase (before connection accepted)
  sopel/irc.py
Labels: Bugfix

#1542 tests: make MockSopelWrapper subclass actual SopelWrapper class
  sopel/bot.py
  sopel/module.py
  sopel/test_tools.py
Labels: Tests

#1561 Unignore more style checks
  dev-requirements.txt
  setup.cfg
  sopel/__init__.py
  sopel/bot.py
  sopel/cli/run.py
  sopel/config/__init__.py
  sopel/modules/calc.py
  sopel/modules/dice.py
  sopel/modules/emoticons.py
  sopel/modules/find.py
  sopel/modules/help.py
  sopel/modules/isup.py
  sopel/modules/search.py
  sopel/modules/tell.py
  sopel/modules/wikipedia.py
  sopel/test_tools.py
  test/test_loader.py
Labels: Tests

#1527 core: fix broken interrupt handling
  sopel/cli/run.py
Labels: Bugfix

#1402 Remove cruft from modules
  sopel/modules/admin.py
  sopel/modules/adminchannel.py
  sopel/modules/announce.py
  sopel/modules/bugzilla.py
  sopel/modules/calc.py
  sopel/modules/clock.py
  sopel/modules/countdown.py
  sopel/modules/currency.py
  sopel/modules/dice.py
  sopel/modules/emoticons.py
  sopel/modules/etymology.py
  sopel/modules/find.py
  sopel/modules/find_updates.py
  sopel/modules/help.py
  sopel/modules/instagram.py
  sopel/modules/ip.py
  sopel/modules/ipython.py
  sopel/modules/isup.py
  sopel/modules/lmgtfy.py
  sopel/modules/meetbot.py
  sopel/modules/ping.py
  sopel/modules/pronouns.py
  sopel/modules/rand.py
  sopel/modules/reddit.py
  sopel/modules/reload.py
  sopel/modules/safety.py
  sopel/modules/search.py
  sopel/modules/seen.py
  sopel/modules/spellcheck.py
  sopel/modules/tell.py
  sopel/modules/tld.py
  sopel/modules/translate.py
  sopel/modules/unicode_info.py
  sopel/modules/units.py
  sopel/modules/uptime.py
  sopel/modules/url.py
  sopel/modules/version.py
  sopel/modules/wikipedia.py
  sopel/modules/wiktionary.py
  sopel/modules/xkcd.py
Labels: Low Priority, Tweak

#1451 help: choose pastebin service for .help output
  sopel/modules/help.py
Labels: Feature

#1403 help: support multiple examples
  sopel/loader.py
  sopel/module.py
  sopel/modules/admin.py
  sopel/modules/help.py
  test/test_loader.py
Labels: Feature, Low Priority

#1563 tools: Overhaul docstrings
  sopel/tools/__init__.py
Labels: Documentation

#1460 config: support comma in config ListAttribute item
  sopel/config/types.py
  test/test_config.py
Labels: Feature, Tweak

#1510 core: handle URL callbacks in coretasks
  sopel/config/core_section.py
  sopel/coretasks.py
  sopel/module.py
  sopel/modules/url.py
  sopel/web.py
  test/test_web.py
Labels: Bugfix, High Priority

#1567 style: replace deprecated `SopelMemory.contains()` with `in`
  sopel/bot.py
  sopel/modules/url.py
Labels: Tweak

#1568 tools: decrease deprecation warning output
  sopel/tools/__init__.py
Labels: Tweak

#1459 help: add config to hide server host from help listing
  sopel/modules/help.py
Labels: Feature

#1573 help: hotfix & small refactor
  sopel/modules/help.py
Labels: Bugfix

#1557 jobs: make JobScheduler easier to stop
  sopel/bot.py
  sopel/tools/jobs.py
  test/tools/test_tools_jobs.py
Labels: High Priority, Tweak

#1575 coretasks: Major rewrite of MODE handling
  sopel/coretasks.py
  sopel/test_tools.py
  test/test_coretasks.py
Labels: Bugfix
