Repository sopel-irc/sopel, pull requests merged in 2019-05, with the labels that each got.

#1430 currency: Moved to different API, support multiple target currencies, cache rates
  sopel/modules/currency.py
Labels: Feature, Low Priority

#1479 plugin: new interface
  docs/source/plugin.rst
  setup.py
  sopel/bot.py
  sopel/cli/config.py
  sopel/cli/run.py
  sopel/cli/utils.py
  sopel/config/__init__.py
  sopel/loader.py
  sopel/modules/reload.py
  sopel/plugins/__init__.py
  sopel/plugins/exceptions.py
  sopel/plugins/handlers.py
  sopel/tools/jobs.py
  test/test_bot.py
  test/test_loader.py
  test/test_plugins.py
Labels: High Priority, Tweak

#1583 cli: `cli.utils.find_config` returns absolute path, as expected
  sopel/cli/utils.py
  test/cli/test_cli_utils.py
Labels: Bugfix

#1580 test_regression: use fresh `MockSopelWrapper`s
  test/test_regression.py
Labels: Tweak

#1587 admin: prevent setting of 'core.owner' setting
  sopel/modules/admin.py
Labels: Bugfix

#1589 Fix up some docstrings for 6.6.x
  sopel/formatting.py
  sopel/tools/__init__.py
  sopel/tools/_events.py
  sopel/tools/target.py
Labels: Documentation

#1500 module: optional `reply` arg for all `require_*` decorators
  sopel/module.py
Labels: Documentation, Medium Priority, Tweak

#1443 wiktionary: refactor/bugfix parsing all possible parts of speech
  sopel/modules/wiktionary.py
Labels: Bugfix, Feature

#1581 remind: use module.interval instead of custom monitoring
  sopel/modules/remind.py
  test/modules/test_modules_remind.py
Labels: High Priority, Tweak

#1498 adminchannel: restore op/voice commands
  sopel/modules/adminchannel.py
Labels: Feature, Low Priority

#1601 build: modernize/expand job matrix
  .travis.yml
  Makefile
Labels: Build, Tests

#1446 db: adding multi database support
  README.rst
  requirements.txt
  sopel/config/core_section.py
  sopel/db.py
Labels: Feature, High Priority

#1503 reddit: short url functionality
  sopel/modules/reddit.py
Labels: Feature, High Priority

#1605 db: fixing db initialization bug
  sopel/db.py
Labels: Bugfix

#1606 Deprecate usage of bot.msg to bot.say
  sopel/bot.py
  sopel/coretasks.py
  sopel/irc.py
  sopel/logger.py
  sopel/module.py
  sopel/modules/admin.py
  sopel/modules/announce.py
  sopel/modules/etymology.py
  sopel/modules/find_updates.py
  sopel/modules/help.py
  sopel/modules/meetbot.py
  sopel/modules/remind.py
  sopel/modules/tell.py
Labels: Tweak

#1608 instagram: Fix for altered JSON key
  sopel/modules/instagram.py
Labels: Bugfix

#1599 admin: Also protect `owner_account` setting
  sopel/modules/admin.py
Labels: Bugfix, Tweak

#1555 test: add an --offline option to pytest
  conftest.py
  sopel/module.py
  sopel/modules/calc.py
  sopel/modules/ip.py
  sopel/modules/search.py
  sopel/modules/translate.py
  sopel/modules/url.py
Labels: Feature, High Priority, Tests

#1614 module: example online argument defaults to False
  sopel/module.py
Labels: Bugfix, Tests

#1615 module: fix examples when pytest isn't installed
  sopel/module.py
Labels: Bugfix, Documentation

#1486 Replace url_callbacks with @url decorators
  sopel/modules/instagram.py
  sopel/modules/reddit.py
  sopel/modules/wikipedia.py
Labels: High Priority, Tweak

#1505 reddit: updating reddit module praw dependency
  requirements.txt
  sopel/modules/reddit.py
Labels: High Priority, Tweak

#1439 url: fixing private URL lookups
  requirements.txt
  sopel/modules/url.py
Labels: Bugfix, High Priority, Tweak

#1612 tld: prevent outputting undecoded HTML entities
  sopel/modules/tld.py
Labels: Bugfix

#1630 coretasks: complete sparse User objects in _record_who()
  sopel/coretasks.py
Labels: Bugfix

#1631 ip: bail on user lookup if host is None
  sopel/modules/ip.py
Labels: Bugfix
