Repository sopel-irc/sopel, pull requests merged in 2019-06, with the labels that each got.

#1634 test: register pytest "online" marker
  .travis.yml
  conftest.py
  dev-requirements.txt
Labels: Bugfix, Tests

#1518 config, bot: Configurable message rate
  sopel/bot.py
  sopel/config/core_section.py
Labels: Feature, High Priority

#1638 bot: fix sometimes-undefined variable in flood protection
  sopel/bot.py
Labels: Bugfix, High Priority

#1611 contrib: remove old database migration tool
  contrib/update_db.py
Labels: Low Priority, Tweak

#1497 Add .invite command
  sopel/modules/invite.py
Labels: Feature, Low Priority

#1512 logging: add format and datefmt to allow configuring the log output from cfg file
  sopel/config/core_section.py
  sopel/logger.py
Labels: Feature, Medium Priority

#1545 spellcheck: add examples
  sopel/modules/spellcheck.py
Labels: Low Priority, Tests

#1513 auth: split 'auth_method' into 'server_auth_method' and 'nick_auth_method'
  sopel/config/core_section.py
  sopel/coretasks.py
  sopel/irc.py
Labels: Feature, High Priority

#1522 install: use setup.cfg to configure Sopel's package metadata
  .travis.yml
  MANIFEST.in
  setup.cfg
  setup.py
  sopel/__init__.py
Labels: Low Priority, Tweak

#1547 logging: use config's basename in log filenames
  sopel/cli/run.py
  sopel/cli/utils.py
  sopel/config/__init__.py
  sopel/irc.py
Labels: Tweak

#1569 modules: always safely set up/clear memory
  sopel/modules/find.py
  sopel/modules/safety.py
  sopel/modules/tell.py
  sopel/modules/url.py
Labels: High Priority, Tweak

#1539 Provide a simpler way to kick users from channels.
  sopel/bot.py
  sopel/modules/adminchannel.py
  sopel/modules/reddit.py
  sopel/modules/safety.py
Labels: Feature, Low Priority

#1576 bot: prevent KeyError from search_url_callbacks
  sopel/bot.py
Labels: Bugfix, High Priority

#1548 dev: adds (optional) pre-commit and pre-push Git hooks
  CONTRIBUTING.md
  Makefile
  contrib/githooks/install-hooks.sh
  contrib/githooks/main-hook.sh
  contrib/githooks/pre-commit
  contrib/githooks/pre-push
  contrib/githooks/uninstall-hooks.sh
Labels: Low Priority, Tweak

#1578 meetbot: Line length, linting, tweaks, fixes
  sopel/modules/meetbot.py
Labels: Tweak

#1607 admin: utilize bot.action
  sopel/modules/admin.py
Labels: Low Priority, Tweak

#1579 Unignore even more style checks
  checkstyle.sh
  dev-requirements.txt
  setup.cfg
  sopel/bot.py
  sopel/cli/run.py
  sopel/coretasks.py
  sopel/irc.py
  sopel/modules/dice.py
  sopel/modules/reddit.py
  sopel/modules/tld.py
  sopel/modules/xkcd.py
  test/modules/test_modules_remind.py
  test/test_web.py
Labels: Medium Priority, Tests
