Repository sopel-irc/sopel, pull requests merged in 2019-10, with the labels that each got.

#1665 tools.events: add alternate spelling of 462 numeric
  sopel/tools/_events.py
Labels: Low Priority, Tweak

#1678 [core] Rework logging
  sopel/bot.py
  sopel/cli/run.py
  sopel/cli/utils.py
  sopel/config/core_section.py
  sopel/coretasks.py
  sopel/irc.py
  sopel/logger.py
  sopel/modules/bugzilla.py
  sopel/modules/currency.py
  sopel/modules/help.py
  sopel/modules/ip.py
  sopel/modules/ipython.py
  sopel/modules/reload.py
  sopel/modules/safety.py
  sopel/tools/__init__.py
  sopel/tools/jobs.py
Labels: Medium Priority, Tweak

#1703 coretasks: fix last_who AttributeError
  sopel/coretasks.py
Labels: Bugfix, Medium Priority

#1708 loader: is_triggerable rejects jobs
  sopel/loader.py
  test/test_loader.py
Labels: Bugfix, High Priority

#1660 module: add action_commands decorator
  sopel/bot.py
  sopel/loader.py
  sopel/module.py
  sopel/tools/__init__.py
  test/test_loader.py
  test/test_module.py
Labels: Feature

#1714 config: add a default `logging_format`
  sopel/config/core_section.py
Labels: Tweak

#1690 config: quote ListAttribute items when required
  sopel/config/types.py
  test/test_config.py
Labels: Bugfix, High Priority

#1577 dice: Add better comment functionality
  sopel/modules/dice.py
Labels: Low Priority, Tweak

#1697 sopel: refactor how the bot manages its connection
  docs/source/bot.rst
  docs/source/irc.rst
  docs/source/package.rst
  sopel/bot.py
  sopel/coretasks.py
  sopel/irc.py
  sopel/irc/__init__.py
  sopel/irc/abstract_backends.py
  sopel/irc/backends.py
  sopel/irc/utils.py
  sopel/test_tools.py
  sopel/tools/jobs.py
  test/irc/test_irc_abstract_backends.py
  test/test_bot.py
  test/test_irc.py
Labels: Tweak

#1723 irc.backends: fix behavior of `core.verify_ssl` setting
  sopel/irc/backends.py
Labels: Bugfix, High Priority

#1724 bot: don't spam logs about preventing run of unmatched funcs
  sopel/bot.py
Labels: Low Priority, Tweak

#1666 coretasks: Only update user 'away' value if value passed is not 'None'
  sopel/coretasks.py
Labels: Low Priority, Tweak

#1672 bot: only suppress echo for PRIVMSG and NOTICE
  sopel/bot.py
Labels: Bugfix, Low Priority, Tweak

#1674 irc: Don't write line ending twice.
  sopel/trigger.py
Labels: Bugfix, Low Priority

#1669 Document `tools.web` package
  docs/source/api.rst
  sopel/tools/web.py
Labels: Documentation

#1675 spellcheck: remove plugin (moving to separate package)
  .travis.yml
  contrib/rpm/sopel.spec.in
  requirements.txt
  sopel/modules/spellcheck.py
Labels: Medium Priority, Windows

#1684 ipython: remove plugin (moving to separate package)
  conftest.py
  contrib/suppress-warnings.py
  requirements.txt
  sopel/modules/ipython.py
Labels: Low Priority
