Repository sopel-irc/sopel, pull requests merged in 2019-12, with the labels that each got.

#1753 safety: rework cache cleanup logic
  sopel/modules/safety.py
Labels: Bugfix, Medium Priority

#1760 reddit: cleanup & various fixes
  sopel/modules/reddit.py
Labels: Bugfix, Medium Priority, Tweak

#1755 db: properly handling threaded sessions
  sopel/db.py
Labels: Bugfix, Medium Priority, Tweak

#1774 db: fix get_uri() to return the actual connection URI
  sopel/db.py
Labels: Bugfix, Medium Priority

#1756 Prepare Sopel to adapt its output when py2 officially dies
  README.rst
  setup.py
  sopel/cli/run.py
Labels: Low Priority, Tweak

#1762 bot, reload: log/show plugin source when reloading
  sopel/bot.py
  sopel/modules/reload.py
Labels: Low Priority, Tweak

#1773 reddit: hide submitted URL if we matched on a media link
  sopel/modules/reddit.py
Labels: Low Priority, Tweak

#1779 find_updates: error handling
  sopel/modules/find_updates.py
Labels: Bugfix, Low Priority, Tweak

#1528 core: perform commands on connect
  docs/source/configuration.rst
  sopel/config/core_section.py
  sopel/coretasks.py
  test/test_coretasks.py
Labels: Feature, Medium Priority

#1751 core: throttle JOIN and WHO commands
  docs/source/configuration.rst
  sopel/config/core_section.py
  sopel/coretasks.py
Labels: Feature, Medium Priority, Tweak

#1758 core: handle 005 RPL_ISUPPORT event
  docs/source/irc.rst
  sopel/coretasks.py
  sopel/irc/__init__.py
  sopel/irc/isupport.py
  test/irc/test_irc_isupport.py
  test/test_coretasks.py
Labels: Feature, High Priority

#1777 tests: migrating db tests to sqlalchemy
  test/test_db.py
Labels: Medium Priority, Tests

#1744 tools: Fix Identifier lowercase
  sopel/db.py
  sopel/tools/__init__.py
  test/test_db.py
Labels: Bugfix, Medium Priority

#1783 db: migrate to connectionless execution for raw sql
  sopel/db.py
Labels: Bugfix, High Priority

#1766 formatting: docstring overhaul
  sopel/formatting.py
Labels: Documentation, Tweak

#1770 module: docstring overhaul & modernization
  sopel/module.py
Labels: Documentation

#1771 tools: subpackage doc overhaul
  docs/source/api.rst
  sopel/tools/__init__.py
  sopel/tools/calculation.py
  sopel/tools/jobs.py
  sopel/tools/target.py
  sopel/tools/time.py
Labels: Documentation

#1772 bot, irc: doc overhaul
  docs/source/trigger.rst
  sopel/bot.py
  sopel/irc/__init__.py
  sopel/irc/abstract_backends.py
  sopel/irc/backends.py
  sopel/irc/utils.py
Labels: Documentation

#1786 docs: Bug, feature, and issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
Labels: Documentation

#1775 logger: doc overhaul
  docs/source/api.rst
  sopel/logger.py
Labels: Documentation

#1776 db, docs: overhaul docstrings & add SQLAlchemy to intersphinx mappings
  docs/source/conf.py
  sopel/db.py
Labels: Documentation

#1778 config: doc overhaul
  docs/source/conf.py
  docs/source/configuration.rst
  sopel/config/__init__.py
  sopel/config/core_section.py
Labels: Documentation

#1782 trigger: doc overhaul
  sopel/trigger.py
  test/test_trigger.py
Labels: Bugfix, Documentation, Tests
