Repository sopel-irc/sopel, pull requests merged in 2019-01, with the labels that each got.

#1413 url: add punctuation cleaning
  sopel/modules/url.py
Labels: Tweak

#1323 docs: Add Open Collective to README.rst
  README.rst
Labels: Documentation

#1417 reddit: match more subdomains
  sopel/modules/reddit.py
Labels: Tweak

#1313 Fix bot.channels.privileges
  sopel/coretasks.py
  sopel/tools/target.py
Labels: Bugfix, High Priority

#1418 search: add contextual warning for 'site:' in DDG query
  sopel/modules/search.py
Labels: Bugfix, Tweak

#1423 Fixing deprecation warnings in tests
  test/test_config.py
Labels: Tests, Tweak

#1419 target: nick property are now updated properly on NICK events
  sopel/tools/target.py
Labels: Bugfix

#1427 lmgtfy: add examples with tests
  sopel/modules/lmgtfy.py
Labels: Tests

#1431 instagram: Update regex to include links with usernames
  sopel/modules/instagram.py
Labels: Tweak

#1432 etymology: Back to basics
  sopel/modules/etymology.py
Labels: Bugfix, Feature

#1437 config: Add default value of 'UTC' to core.default_timezone
  sopel/config/core_section.py
Labels: Tweak

#1441 movie: removing broken module
  conftest.py
  sopel/modules/movie.py
Labels: Feature

#1314 reload: Recurse into packaged modules
  sopel/modules/reload.py
Labels: Bugfix, High Priority

#1454 Don't require pyenchant on Python 3.7 or above
  requirements.txt
Labels: Build, Tweak

#1458 setup.py: add Trove classifiers
  setup.py
Labels: Build, Tweak

#1424 loader: test coverage
  test/test_loader.py
Labels: Tests

#1448 core: properly truncate long messages with 2-byte characters
  sopel/bot.py
  sopel/irc.py
  sopel/tools/__init__.py
  test/test_tools.py
Labels: Bugfix

#1457 coretasks: split AUTHENTICATE token in 400-byte chunks
  sopel/coretasks.py
Labels: Bugfix

#1429 run_script: clean up & reorganize code
  sopel.py
  sopel/config/__init__.py
  sopel/run_script.py
  test/test_run_script.py
Labels: Tests, Tweak

#1333 Implement restart functionality
  sopel/__init__.py
  sopel/irc.py
  sopel/modules/admin.py
  sopel/run_script.py
Labels: Feature
