Repository sopel-irc/sopel, pull requests merged in 2020-12, with the labels that each got.

#1959 Path setting and doc tweaks; meetbot enforcement change
  docs/source/configuration.rst
  sopel/config/core_section.py
  sopel/modules/ip.py
  sopel/modules/meetbot.py
Labels: Documentation, Tweak

#1960 test: update VCR.py cassettes
  Makefile
  conftest.py
  sopel/modules/search.py
  test/vcr/modules/currency/test_example_exchange_cmd_0.yaml
  test/vcr/modules/currency/test_example_exchange_cmd_1.yaml
  test/vcr/modules/isup/test_example_isup_0.yaml
  test/vcr/modules/py/test_example_py_0.yaml
  test/vcr/modules/search/test_example_duck_0.yaml
  test/vcr/modules/search/test_example_duck_1.yaml
  test/vcr/modules/search/test_example_suggest_0.yaml
  test/vcr/modules/search/test_example_suggest_2.yaml
  test/vcr/modules/translate/test_example_tr2_0.yaml
  test/vcr/modules/translate/test_example_tr2_1.yaml
  test/vcr/modules/translate/test_example_tr2_2.yaml
  test/vcr/modules/url/test_example_title_command_0.yaml
Labels: Build, Tests

#1961 admin: add .chanlist command to show what channels Sopel is in
  sopel/modules/admin.py
Labels: Feature

#1964 Audit docs (mostly) for incorrect use of the term "module"
  sopel/coretasks.py
  sopel/irc/__init__.py
  sopel/irc/utils.py
  sopel/logger.py
  sopel/plugins/__init__.py
  sopel/plugins/handlers.py
Labels: Documentation, Tweak

#1965 choose: safely handle formatted options
  sopel/formatting.py
  sopel/modules/choose.py
  test/modules/test_modules_choose.py
  test/modules/test_modules_isup.py
Labels: Bugfix

#1967 plugin: keep old-school plugin devs happy w/plural command decorators
  sopel/module.py
  sopel/plugin.py
Labels: Tweak

#1968 tld: small tweak to parser's handling of superscript
  sopel/modules/tld.py
Labels: Tweak

#1969 cli, setup: hard-code Python 2 EOL message
  setup.py
  sopel/cli/run.py
Labels: Tweak

#1970 tld: Use Wiki API
  sopel/modules/tld.py
Labels: Tweak

#1971 core: quit after SASL Auth failed
  sopel/coretasks.py
Labels: Bugfix, Low Priority

#1973 config: warn if unexpected settings exist
  sopel/bot.py
  sopel/config/__init__.py
  sopel/config/types.py
  test/test_config.py
Labels: Feature, Low Priority

#1975 plugin: replace intent by ctcp
  docs/source/plugin.rst
  docs/source/plugin/anatomy.rst
  sopel/module.py
  sopel/modules/seen.py
  sopel/modules/version.py
  sopel/plugin.py
  sopel/trigger.py
  test/test_plugin.py
  test/test_trigger.py
Labels: Feature

#1983 irc: test sopel.irc.utils.safe function
  sopel/irc/utils.py
  test/irc/test_irc_utils.py
Labels: Low Priority, Tests

#1984 tools: more tests for sopel.tools.time
  test/test_tools.py
  test/tools/test_tools_time.py
Labels: Low Priority, Tests

#1987 reddit: fix floating point issue on %
  sopel/modules/reddit.py
Labels: Bugfix, Low Priority

#1982 plugin: new `require_bot_privilege` decorator
  docs/source/plugin/anatomy.rst
  sopel/bot.py
  sopel/modules/adminchannel.py
  sopel/plugin.py
  sopel/tools/target.py
  test/test_bot.py
  test/test_plugin.py
  test/test_tools.py
  test/tools/test_tools_target.py
Labels: Feature, Low Priority

#1985 tld: fix parsing stored cache timestamps that are invalid or on py2
  sopel/modules/tld.py
Labels: Bugfix, Tweak
