Repository sopel-irc/sopel, pull requests merged in 2020-08, with the labels that each got.

#1919 build: cap `update-checker` version on older Pythons without f-strings
  requirements.txt
Labels: Build

#1915 ip: fix case sensitivity of querying by nickname
  sopel/modules/ip.py
Labels: Bugfix

#1904 plugins: handle URL callbacks in new rule system
  sopel/bot.py
  sopel/config/core_section.py
  sopel/irc/__init__.py
  sopel/loader.py
  sopel/modules/bugzilla.py
  sopel/modules/url.py
  sopel/modules/wikipedia.py
  sopel/plugin.py
  sopel/plugins/exceptions.py
  sopel/plugins/rules.py
  sopel/test_tools.py
  sopel/tests/factories.py
  sopel/tools/__init__.py
  sopel/trigger.py
  test/modules/test_modules_url.py
  test/plugins/test_plugins_rules.py
  test/test_bot.py
  test/test_loader.py
  test/test_plugin.py
  test/test_tools.py
Labels: Feature

#1910 find: switch to deque for recent line storage
  sopel/modules/find.py
Labels: Low Priority, Tweak

#1914 reddit: handle new gallery view by showing submission info
  sopel/modules/reddit.py
Labels: Feature

#1916 wikipedia: implement language preferences in DB for channels & nicks
  sopel/modules/wikipedia.py
Labels: Feature, Medium Priority

#1927 jobs: fix job 'running state'
  sopel/tools/jobs.py
Labels: Bugfix

#1918 trigger: add a plain attribute to PreTrigger and Trigger
  sopel/formatting.py
  sopel/trigger.py
  test/test_formatting.py
  test/test_trigger.py
Labels: Feature, Low Priority

#1920 tools.compile_rule: better whitespace handling for `$nick` placeholder
  sopel/tools/__init__.py
Labels: Tweak

#1924 plugin: rename plural decorators to be consistent
  docs/source/plugin.rst
  sopel/config/core_section.py
  sopel/module.py
  sopel/plugin.py
  sopel/trigger.py
Labels: Tweak
