Repository sopel-irc/sopel, pull requests merged in 2020-06, with the labels that each got.

#1880 admin: refactor silly nested `if` in hold_ground()
  sopel/modules/admin.py
Labels: Tweak

#1882 cli: fix SOPEL_CONFIG env var broken usage
  sopel/cli/run.py
  sopel/cli/utils.py
  test/cli/test_cli_run.py
  test/cli/test_cli_utils.py
Labels: Bugfix, High Priority

#1866 doc: add more examples to core_section
  docs/source/configuration.rst
  sopel/config/core_section.py
Labels: Documentation

#1873 rules: refactoring of Sopel's rule system to an object-oriented approach
  docs/source/plugin.rst
  sopel/bot.py
  sopel/config/core_section.py
  sopel/loader.py
  sopel/module.py
  sopel/plugins/__init__.py
  sopel/plugins/handlers.py
  sopel/plugins/rules.py
  sopel/tools/__init__.py
  test/plugins/test_plugins_rules.py
  test/test_bot.py
  test/test_commands.py
  test/test_loader.py
  test/test_module.py
  test/test_tools.py
Labels: Feature, High Priority

#1878 clock: add help prefix to output examples
  sopel/modules/clock.py
Labels: Documentation, Low Priority

#1794 Docstring style guide
  CONTRIBUTING.md
Labels: Documentation

#1881 rules: add find and search rules
  sopel/bot.py
  sopel/loader.py
  sopel/module.py
  sopel/plugins/rules.py
  test/plugins/test_plugins_rules.py
  test/test_bot.py
  test/test_loader.py
  test/test_module.py
Labels: Feature, High Priority

#1889 reddit: fix slash-info wrongly calling output funcs as `commanded`
  sopel/modules/reddit.py
Labels: Bugfix

#1890 irc: tweak backend interface
  sopel/bot.py
  sopel/irc/abstract_backends.py
  sopel/irc/backends.py
  sopel/logger.py
  sopel/tests/mocks.py
  test/irc/test_irc_abstract_backends.py
Labels: Medium Priority, Tweak

#1892 reddit: use new `find` rule type to get all slash-refs in line
  sopel/modules/reddit.py
Labels: Tweak

#1893 bot: signal handler now checks if the bot is connected
  sopel/bot.py
  sopel/cli/run.py
  sopel/irc/__init__.py
  sopel/irc/backends.py
Labels: Bugfix

#1894 rules, emoticons: action commands & commands working together at last
  sopel/module.py
  sopel/modules/emoticons.py
  test/test_module.py
Labels: Feature

#1879 config: add is_secret attribute to use getpass hidden input
  sopel/config/core_section.py
  sopel/config/types.py
  sopel/modules/admin.py
Labels: Bugfix

#1891 jobs: prevent parallel execution and plugin specific scheduler
  docs/source/api.rst
  docs/source/plugin.rst
  sopel/bot.py
  sopel/coretasks.py
  sopel/irc/backends.py
  sopel/plugins/jobs.py
  sopel/tools/jobs.py
  test/tools/test_tools_jobs.py
Labels: Bugfix, Feature, High Priority

#1897 url: add auto-title config option & debug logging
  sopel/modules/url.py
Labels: Feature, Low Priority
