Repository sopel-irc/sopel, pull requests merged in 2020-05, with the labels that each got.

#1854 search: Bing regex needs to be less specific
  sopel/modules/search.py
Labels: Bugfix

#1855 loader: make sure URL callbacks are ready to pass through `bot.call()`
  sopel/loader.py
  test/test_loader.py
Labels: Bugfix

#1763 reddit: subreddit handling for r/all and r/popular
  sopel/modules/reddit.py
Labels: Feature, Low Priority

#1857 docs: remove duplicate entries for `bot.{name,nick,user}`
  docs/source/bot.rst
  sopel/irc/__init__.py
Labels: Build, Documentation

#1858 xkcd: Parse latest comic when base URL is linked
  sopel/modules/xkcd.py
Labels: Feature

#1163 wikipedia: retrieve section summaries
  sopel/modules/wikipedia.py
Labels: Feature

#1863 bot: fix plugin name in _command_groups
  sopel/bot.py
Labels: Bugfix

#1861 docs: add examples for owner/admins config values
  docs/source/configuration.rst
Labels: Documentation

#1178 Move etymology lookup to wiktionary
  sopel/modules/etymology.py
  sopel/modules/wiktionary.py
Labels: Feature, Medium Priority

#1856 search: cleanup dead stuff
  sopel/modules/search.py
Labels: Tweak

#1871 url: tweak default_headers and max_bytes for improved URL titles
  sopel/modules/url.py
Labels: Tweak

#1872 tools: add `warning_in` arg to `@deprecated`; deprecate `get_input`
  sopel/tools/__init__.py
Labels: Tweak

#1875 ping: add .ping command
  sopel/modules/ping.py
Labels: Feature
