Repository sopel-irc/sopel, pull requests merged in 2020-04, with the labels that each got.

#1828 clock: add feedback to `.setchanneltz` if not OP
  sopel/modules/clock.py
Labels: Bugfix

#1829 units: fix mass when given exactly 1 pound
  sopel/modules/units.py
Labels: Bugfix

#1831 remind: fix loading DB when a reminder contains italics
  sopel/modules/remind.py
  sopel/modules/tell.py
  test/modules/test_modules_remind.py
  test/modules/test_modules_tell.py
Labels: Bugfix, Tests

#1840 bot: fix per-channel configuration by plugin names
  sopel/bot.py
  sopel/plugins/handlers.py
Labels: Bugfix

#1832 Patch `version` variable not being used in regex
  sopel/__init__.py
Labels: Bugfix

#1845 bot: route URL callbacks through `bot.call()` too
  sopel/bot.py
  sopel/coretasks.py
Labels: Bugfix

#1851 safety: handle missing VirusTotal scan data
  sopel/modules/safety.py
Labels: Bugfix

#1843 tools.time: zero is a special case for `seconds_to_human()`
  sopel/tools/time.py
Labels: Bugfix

#1844 docs: modify channel config examples to show password/key usage
  docs/source/configuration.rst
  sopel/config/core_section.py
  sopel/tools/time.py
Labels: Documentation, Tweak

#1848 xkcd: suppress link if triggered by a URL match
  sopel/modules/xkcd.py
Labels: Bugfix

#1849 reddit: grammatically correct point/points depending on score
  sopel/modules/reddit.py
Labels: Bugfix, Tweak

#1852 search: some Bing fixes (UA spoofing, example test, regex)
  sopel/modules/search.py
Labels: Bugfix, Tweak
