Repository sopel-irc/sopel, pull requests merged in 2020-09, with the labels that each got.

#1929 irc, config: config options for flood penalty on longer messages
  docs/source/configuration.rst
  sopel/config/core_section.py
  sopel/irc/__init__.py
Labels: Feature

#1922 cli: modernize docstrings
  sopel/cli/config.py
  sopel/cli/plugins.py
  sopel/cli/run.py
  sopel/cli/utils.py
Labels: Documentation

#1923 docs: the plugin chapter
  docs/source/bot.rst
  docs/source/index.rst
  docs/source/package.rst
  docs/source/plugin.rst
  docs/source/plugin/anatomy.rst
  docs/source/plugin/bot.rst
  docs/source/plugin/decorators.rst
  docs/source/plugin/internals.rst
  docs/source/plugin/what.rst
  sopel/plugin.py
Labels: Documentation

#1937 plugins: check consistency of plugin code and their output formatting
  sopel/modules/admin.py
  sopel/modules/adminchannel.py
  sopel/modules/announce.py
  sopel/modules/bugzilla.py
  sopel/modules/calc.py
  sopel/modules/choose.py
  sopel/modules/clock.py
  sopel/modules/countdown.py
  sopel/modules/currency.py
  sopel/modules/dice.py
  sopel/modules/emoticons.py
  sopel/modules/find.py
  sopel/modules/find_updates.py
  sopel/modules/help.py
  sopel/modules/instagram.py
  sopel/modules/invite.py
  sopel/modules/ip.py
  sopel/modules/isup.py
  sopel/modules/lmgtfy.py
  sopel/modules/meetbot.py
  sopel/modules/ping.py
  sopel/modules/pronouns.py
  sopel/modules/py.py
  sopel/modules/rand.py
  sopel/modules/reddit.py
  sopel/modules/reload.py
  sopel/modules/remind.py
  sopel/modules/safety.py
  sopel/modules/search.py
  sopel/modules/seen.py
  sopel/modules/tell.py
  sopel/modules/tld.py
  sopel/modules/translate.py
  sopel/modules/unicode_info.py
  sopel/modules/units.py
  sopel/modules/uptime.py
  sopel/modules/url.py
  sopel/modules/version.py
  sopel/modules/wikipedia.py
  sopel/modules/wiktionary.py
  sopel/modules/xkcd.py
Labels: Tweak

#1932 docs: add space before attribute lists
  docs/source/_static/custom.css
Labels: Documentation, Tweak

#1936 loader, plugin: load decorated callables only
  sopel/loader.py
  sopel/plugin.py
  test/test_loader.py
Labels: Bugfix

#1930 core: change/recover in-use nick; fix obsolete USER command syntax
  sopel/coretasks.py
  sopel/irc/__init__.py
  sopel/irc/abstract_backends.py
  sopel/irc/backends.py
  test/test_irc.py
Labels: Feature

#1939 tld: comprehensive rewrite
  sopel/modules/tld.py
Labels: Feature

#1940 isup: fix error-series HTTP status codes; get away from assuming TLD
  sopel/modules/isup.py
  test/modules/test_modules_isup.py
Labels: Bugfix, Tweak

#1938 tools: new `SopelIdentifierMemory` class
  sopel/bot.py
  sopel/modules/find.py
  sopel/modules/translate.py
  sopel/modules/url.py
  sopel/test_tools.py
  sopel/tools/__init__.py
  test/test_tools.py
Labels: Feature
