Repository sopel-irc/sopel, pull requests merged in 2020-10, with the labels that each got.

#1948 tools: make `time` and `web` always accessible by importing `tools`
  sopel/tools/__init__.py
Labels: Tweak

#1859 announce: send announces to TARGMAX channels at once, if advertised
  sopel/modules/announce.py
Labels: Tweak

#1928 coretasks: better SASL handling
  sopel/coretasks.py
Labels: Tweak

#1933 config: small refactoring and unit tests for types
  sopel/config/types.py
  sopel/modules/admin.py
  test/config/test_config_types.py
Labels: Tests, Tweak

#1976 core: fix invalid usage of r-string for SASL auth token
  sopel/coretasks.py
Labels: Bugfix, High Priority

#1977 core, test: make SASL PLAIN token generation testable (and test it)
  sopel/coretasks.py
  test/test_coretasks.py
Labels: Tests, Tweak
