Repository sopel-irc/sopel, pull requests merged in 2020-03, with the labels that each got.

#1764 reddit: Reduce try/except size for redditor_info
  sopel/modules/reddit.py
Labels: Tweak

#1814 reddit: show shortlink of post when expanding media URLs
  sopel/modules/reddit.py
Labels: Tweak

#1820 irc.backends: Hotfix thread error on connection loss
  sopel/irc/backends.py
Labels: Bugfix

#1822 cli.run: Show loaded config file at startup
  sopel/cli/run.py
Labels: Tweak

#1825 cli.utils: fix outdated `find_config()` docstring example
  sopel/cli/utils.py
Labels: Bugfix, Documentation

#1827 reddit: Allow `%` in post URLs
  sopel/modules/reddit.py
Labels: Bugfix
