Repository sopel-irc/sopel, pull requests merged in 2020-01, with the labels that each got.

#1797 ip: update MaxMind GeoLite2 database fetching
  sopel/modules/ip.py
Labels: Bugfix, High Priority

#1788 url: Ignore more invalid URLs
  sopel/modules/url.py
  test/modules/test_modules_url.py
Labels: Bugfix

#1795 setup: fix/update python version checks
  setup.py
Labels: Bugfix

#1791 adminchannel: hostmask configuration fix
  sopel/modules/adminchannel.py
Labels: Bugfix

#1800 setup, cli.run: parity between py2 checks & code cleanup
  setup.py
  sopel/cli/run.py
Labels: Tweak

#1787 Setup metadata overhaul
  CREDITS
  setup.cfg
  setup.py
Labels: Tweak

#1671 core: add inspircd operprefix !/+y channel mode
  sopel/coretasks.py
  sopel/module.py
Labels: Low Priority, Tweak

#1802 safety: properly check whether cache is too big
  sopel/modules/safety.py
Labels: Bugfix

#1790 Changelog for 7.0.0
  NEWS
Labels: Documentation

#1806 coretasks: make handle_url_callbacks blockable
  sopel/coretasks.py
Labels: Tweak

#1807 requirements: tighten up version ranges
  NEWS
  requirements.txt
Labels: Tweak

#1808 bot: require callback to unregister URL handler
  sopel/bot.py
  sopel/modules/bugzilla.py
  sopel/test_tools.py
  test/test_bot.py
Labels: Tweak

#1811 db: raw sql functionality and session object api
  NEWS
  README.rst
  docs/source/configuration.rst
  sopel/config/core_section.py
  sopel/db.py
Labels: Tweak

#1813 Final 7.0 docs cleanup
  NEWS
  docs/source/api.rst
  docs/source/conf.py
  docs/source/trigger.rst
  sopel/bot.py
  sopel/config/__init__.py
  sopel/config/types.py
  sopel/db.py
  sopel/irc/abstract_backends.py
  sopel/module.py
  sopel/plugins/handlers.py
  sopel/test_tools.py
  sopel/tests/factories.py
  sopel/tools/__init__.py
  sopel/tools/time.py
  sopel/trigger.py
Labels: Documentation
