Repository sopel-irc/sopel, pull requests merged in 2020-11, with the labels that each got.

#1972 ci: test on Python 3.9
  .travis.yml
Labels: Build

#1941 coretasks: assume + only if core.modes does not start with + or -
  sopel/coretasks.py
Labels: Low Priority, Tweak

#1942 coretasks, admin: minor style fix for bot.write
  sopel/coretasks.py
  sopel/modules/admin.py
Labels: Low Priority, Tweak

#1943 bot: prevent sys.exit when loading plugin to crash the bot
  sopel/bot.py
Labels: Bugfix

#1944 plugins: command-regexp functions are now private
  sopel/plugins/rules.py
  sopel/test_tools.py
  sopel/tools/__init__.py
  test/plugins/test_plugins_rules.py
  test/test_tools.py
Labels: Tweak

#1951 coretasks: reduce "useless MODE message" logspam
  sopel/coretasks.py
Labels: Tweak

#1952 version: tweak docstring for clarification
  sopel/modules/version.py
Labels: Documentation, Tweak

#1949 tld: add .tldcache command
  sopel/modules/tld.py
Labels: Feature

#1989 requirements, url: adapt to urllib3 exception type change
  requirements.txt
  sopel/modules/url.py
Labels: Build

#1950 isup: more specific errors
  sopel/modules/isup.py
  test/modules/test_modules_isup.py
Labels: Tweak

#1953 admin, pronouns, py: argument checking, logging, and better reply on error messages
  sopel/modules/admin.py
  sopel/modules/pronouns.py
  sopel/modules/py.py
Labels: Bugfix, Tweak

#1954 reddit: remove stray hard-coded message prefix missed in #1937
  sopel/modules/reddit.py
Labels: Bugfix

#1955 find_updates: restore unstable release handling
  sopel/__init__.py
  sopel/modules/find_updates.py
Labels: Bugfix, Tweak

#1956 adminchannel: use `TOPICLEN` token from `ISUPPORT` if available
  sopel/modules/adminchannel.py
Labels: Feature

#1958 bot, irc: in `bot.say()`, fill IRC line if possible & add optional truncation indicator
  setup.cfg
  sopel/bot.py
  sopel/irc/__init__.py
  test/test_irc.py
Labels: Feature
