Repository sopel-irc/sopel, pull requests merged in 2021-07, with the labels that each got.

#2088 coretasks: handle `BOT` ISUPPORT token & mode
  sopel/coretasks.py
  test/test_coretasks.py
Labels: Feature, Low Priority

#2102 coretasks: add `userhost-in-names` CAP and `UHNAMES` ISUPPORT token
  sopel/coretasks.py
  test/test_coretasks.py
Labels: Medium Priority, Tweak

#2100 coretasks, irc: implement CertFP / SASL EXTERNAL authentication
  docs/source/configuration.rst
  sopel/config/core_section.py
  sopel/coretasks.py
  sopel/irc/__init__.py
  sopel/irc/backends.py
Labels: Feature

#2095 irc: Use repr() and don't strip() rawlog, log charset guess failures
  sopel/irc/__init__.py
  sopel/irc/backends.py
Labels: Breaking Change, Bugfix, Tweak

#2104 admin: add .raw command to send raw IRC messages
  sopel/modules/admin.py
Labels: Feature

#2116 coretasks, test: support CHGHOST command/capability
  sopel/coretasks.py
  test/test_coretasks.py
Labels: Feature

#2117 Replace (almost) all usage of `sopel.module` with `sopel.plugin`
  sopel/coretasks.py
  test/modules/test_modules_url.py
  test/plugins/test_plugins_rules.py
  test/test_bot.py
  test/test_loader.py
  test/test_plugins.py
  test/tools/test_tools_jobs.py
Labels: Tweak

#2119 plugins: don't search in `~/.sopel/modules` by default any more
  sopel/plugins/__init__.py
  sopel/plugins/handlers.py
Labels: Breaking Change, Documentation, Tweak

#2121 bot: remove `bot.memory['url_callbacks]` and use internal state
  sopel/bot.py
  test/test_bot.py
Labels: Breaking Change, Medium Priority, Tweak

#2143 wikipedia: log a warning if `lang_per_channel` is used for a channel
  sopel/modules/wikipedia.py
Labels: Medium Priority, Tweak

#2122 formatting: `colors` is now an Enum
  sopel/formatting.py
Labels: Low Priority, Tweak

#2127 tools.events: convert to `Enum`
  sopel/tools/_events.py
Labels: Breaking Change, Low Priority, Tweak

#2151 invite: handle expected possible exception
  sopel/modules/invite.py
Labels: Bugfix, Low Priority

#2123 conftest: remove hacks/shims for running tests on Python 3.3
  conftest.py
Labels: Build, Housekeeping, Low Priority, Tests, Tweak

#2124 plugins.rules.URLCallback: use `yield from` expression
  sopel/plugins/rules.py
Labels: Housekeeping, Low Priority, Tweak

#2087 config, db: support `db_url` setting to override the individual options
  docs/source/configuration.rst
  sopel/config/core_section.py
  sopel/db.py
Labels: Feature, Medium Priority

#2126 loader: drop compatibility code for old-style Phenny/Jenni modules
  sopel/loader.py
  test/test_loader.py
Labels: Breaking Change, Housekeeping, Low Priority, Tests, Tweak

#2129 bot, coretasks: remove redundant `bot.privileges` data structure
  sopel/bot.py
  sopel/coretasks.py
  test/test_regression.py
Labels: Breaking Change, High Priority, Housekeeping

#2153 translate: catch requests exceptions
  sopel/modules/translate.py
Labels: Bugfix

#2154 pronouns: add `.clearpronouns` command
  sopel/modules/pronouns.py
Labels: Feature, Low Priority

#2128 web: remove old `sopel.web` module
  sopel/web.py
Labels: Breaking Change, Housekeeping, Low Priority

#2156 Revert "bot: deprecate `search_url_callbacks()` method"
  sopel/bot.py
Labels: Tweak

#2132 tools.time: handle aware datetimes too in `format_time()`
  sopel/tools/time.py
  test/tools/test_tools_time.py
Labels: Breaking Change, Feature, Low Priority
