Repository sopel-irc/sopel, pull requests merged in 2021-11, with the labels that each got.

#2174 Update to check for proper UTF8 on Windows
  sopel/__init__.py
Labels: Windows, Bugfix

#2201 wikipedia: handle mobile links
  sopel/modules/wikipedia.py
Labels: Bugfix

#2204 web: use `html.unescape()` when available (Python 3.4+)
  sopel/tools/web.py
Labels: Bugfix

#2181 clock: add unset functionality
  sopel/modules/clock.py
Labels: Feature

#2131 irc: rework parsing of modestrings
  docs/source/irc.rst
  sopel/bot.py
  sopel/coretasks.py
  sopel/irc/modes.py
  test/irc/test_irc_modes.py
  test/test_coretasks.py
Labels: Medium Priority, Tweak

#2208 reddit: fix matching twice for reddit.com without www.
  sopel/modules/reddit.py
  test/modules/test_modules_reddit.py
Labels: Bugfix

#2200 isupport: maintain PREFIX ordering
  sopel/irc/isupport.py
  test/irc/test_irc_isupport.py
Labels: Bugfix
