Repository sopel-irc/sopel, pull requests merged in 2021-03, with the labels that each got.

#2028 url: urlexclude/allow commands; auto-title ignores URLs in ANY other command
  sopel/modules/url.py
Labels: Feature

#2029 url: restore error output when not all `.title` URLs could be fetched
  sopel/modules/url.py
Labels: Bugfix, Low Priority, Tweak

#2046 tools: add `stack_frame` kwarg to `deprecated` decorator
  sopel/tools/__init__.py
Labels: Feature

#2033 bot: emit warning when memory['url_callbacks'] is used manually in a plugin's setup
  sopel/bot.py
Labels: Tweak
