Repository sopel-irc/sopel, pull requests merged in 2021-02, with the labels that each got.

#2007 remind: .reminders count/forget command
  sopel/modules/remind.py
Labels: Feature

#2011 rules: add get-all methods for all types of rules
  sopel/plugins/rules.py
  test/plugins/test_plugins_rules.py
Labels: Feature

#2013 docs: do it with style: interact with the bot
  docs/source/_static/custom.css
  docs/source/plugin/bot.rst
Labels: Documentation, Low Priority

#2014 find: format replacement text instead of "meant"
  sopel/modules/find.py
Labels: Tweak

#2018 coretasks: update event priorities from high to medium
  docs/source/plugin.rst
  docs/source/plugin/advanced.rst
  sopel/coretasks.py
Labels: Documentation, Tweak

#2020 logging: don't crash if backend is uninitialized
  sopel/logger.py
Labels: Bugfix

#2023 coretasks: tweak dict usage
  sopel/coretasks.py
Labels: Tweak

#2025 reddit: show singular "comment" in post output when appropriate
  sopel/modules/reddit.py
Labels: Bugfix

#2026 tools.time: improve seconds_to_human
  sopel/tools/time.py
  test/tools/test_tools_time.py
Labels: Feature, Tweak

#2027 tools, loader, plugins.rules: deprecate compile_rule
  sopel/loader.py
  sopel/plugins/rules.py
  sopel/tools/__init__.py
  test/test_loader.py
Labels: Documentation, Tweak
