Repository sopel-irc/sopel, pull requests merged in 2021-01, with the labels that each got.

#1994 tell: remove @ from start of nicknames
  sopel/modules/tell.py
Labels: Low Priority, Tweak

#1995 modules: use `bot.say()`'s `trailing` parameter
  sopel/modules/instagram.py
  sopel/modules/reddit.py
  sopel/modules/tld.py
  sopel/modules/wikipedia.py
  sopel/modules/wiktionary.py
Labels: Tweak

#1997 coretasks: NAMESX when multi-prefix is not available
  sopel/coretasks.py
  test/test_coretasks.py
Labels: Feature

#1998 coretasks: WHOX availability checks use ISUPPORT
  sopel/coretasks.py
Labels: Medium Priority, Tweak

#2000 instagram: remove fragile plugin
  sopel/modules/instagram.py
Labels: Medium Priority

#2003 tests: deprecate test_tools; replace with tests.pytest_plugin
  sopel/plugin.py
  sopel/test_tools.py
  sopel/tests/pytest_plugin.py
Labels: Low Priority, Tweak

#2004 loader: improve docstrings
  sopel/loader.py
Labels: Documentation

#2001 coretasks: trying to improve docstrings
  sopel/coretasks.py
Labels: Documentation

#2002 plugins: improve docstrings according to project standards
  sopel/plugins/__init__.py
  sopel/plugins/handlers.py
  sopel/plugins/jobs.py
  sopel/plugins/rules.py
Labels: Documentation

#2015 isupport: return empty CHANMODES if unavailable
  sopel/irc/isupport.py
  test/irc/test_irc_isupport.py
Labels: Tweak

#1981 adminchannel: allow non-op .topic in -t channels
  sopel/modules/adminchannel.py
Labels: Bugfix, Low Priority

#2005 sopel: using utcnow and fixing minor issues with datetime
  sopel/bot.py
  sopel/irc/__init__.py
  sopel/irc/backends.py
  sopel/trigger.py
Labels: Bugfix, Tweak

#2006 doc: add examples to configure auth
  docs/source/configuration.rst
Labels: Documentation

#2012 safety: switch from malwaredomains (dead) to StevenBlack hosts list
  sopel/modules/safety.py
Labels: Bugfix

#1993 find: use slash or pipe in sed-like command
  sopel/modules/find.py
Labels: Feature, Low Priority
