Repository sopel-irc/sopel, pull requests merged in 2021-06, with the labels that each got.

#2084 config: fix BooleanAttribute default=True
  sopel/config/types.py
  test/test_config.py
Labels: Bugfix

#2085 contrib: cleanup
  contrib/release.sh
  contrib/rpm/makerpm.py
  contrib/rpm/sopel.spec.in
Labels: Low Priority, Tweak

#2086 plugins.rules: `URLCallback` shall handle invalid URLs by ignoring them
  sopel/plugins/rules.py
  test/plugins/test_plugins_rules.py
Labels: Bugfix

#2090 docs: fix some outdated stuff about configuration/logging
  docs/source/configuration.rst
  sopel/config/__init__.py
Labels: Documentation

#2091 coretasks: fix bad WHO tracking endless loop
  sopel/coretasks.py
Labels: Bugfix, High Priority

#2094 tests: fix+add ENV override tests
  test/cli/test_cli_run.py
  test/cli/test_cli_utils.py
  test/test_config.py
Labels: Bugfix, Low Priority, Tests

#2096 trigger: document that `args` is a list
  sopel/trigger.py
Labels: Bugfix, Documentation

#2097 coretasks: Strip Unreal's extra empty MODE arg
  sopel/coretasks.py
  test/test_coretasks.py
Labels: Bugfix

#2098 coretasks: Clear prior modes on RPL_CHANNELMODEIS
  sopel/coretasks.py
  test/test_coretasks.py
Labels: Bugfix

#2105 docs: config/auth: clarify auth_username, etc
  docs/source/configuration.rst
  sopel/config/core_section.py
Labels: Documentation

#2106 tell: use correct verb when `tellee == bot.nick`; use `NICKLEN` if available
  sopel/modules/tell.py
Labels: Bugfix, Tweak

#2108 docs: more details about users in channels
  docs/source/plugin/bot.rst
  sopel/plugin.py
  sopel/tools/__init__.py
  sopel/trigger.py
Labels: Documentation, High Priority

#2103 safety: prevent UnicodeDecodeError on startup under py2
  sopel/modules/safety.py
Labels: Bugfix

#2112 docs: be even more specific that `owner` is ALWAYS required
  docs/source/configuration.rst
Labels: Documentation, Tweak

#2125 docs: clarify relationship between `owner` and `owner_account` (again)
  docs/source/configuration.rst
  docs/source/plugin/anatomy.rst
Labels: Documentation, Tweak

#1966 wikipedia: modify command names
  sopel/modules/wikipedia.py
Labels: Breaking Change, Tweak, hacktoberfest-accepted

#2070 pronouns: accept they/them and they/them/theirs
  sopel/modules/pronouns.py
Labels: Feature
