Repository sopel-irc/sopel, pull requests merged in 2021-05, with the labels that each got.

#2053 currency: improve error handling
  sopel/modules/currency.py
Labels: Bugfix

#2056 find_updates, test: create test to verify error case behavior
  dev-requirements.txt
  sopel/modules/find_updates.py
  test/modules/test_modules_find_updates.py
Labels: Low Priority, Tests

#2059 core, modules: replace deprecated uses of `parse=bool` in settings
  sopel/config/core_section.py
  sopel/modules/admin.py
  sopel/modules/currency.py
  sopel/modules/help.py
  sopel/modules/safety.py
  sopel/modules/tell.py
  sopel/modules/url.py
Labels: High Priority, Tweak

#2060 currency: API switch & backup option
  sopel/modules/currency.py
  test/vcr/modules/currency/test_example_exchange_cmd_0.yaml
Labels: Bugfix, High Priority

#2058 tools: Convert `deprecated` decorator to use logging output
  sopel/tools/__init__.py
Labels: Feature, Tweak

#2063 isup: fix double output, and add tests
  sopel/modules/isup.py
  test/modules/test_modules_isup.py
  test/vcr/modules/isup/test_example_isup_0.yaml
Labels: Bugfix, Medium Priority, Tests

#2064 wiktionary: fix fetching etymology containing citations
  sopel/modules/wiktionary.py
Labels: Bugfix, Medium Priority

#1988 currency: add thousands separator, dynamic precision, and optional HTTPS for Fixer
  sopel/modules/currency.py
Labels: Tweak

#2065 tests: `MockIRCServer` methods should block by default
  sopel/tests/factories.py
  sopel/tests/mocks.py
  sopel/tests/pytest_plugin.py
  test/modules/test_modules_isup.py
Labels: Tests

#2066 find: don't output useless bold formatting for empty replacement
  sopel/modules/find.py
Labels: Low Priority, Tweak

#2067 docs: plugin tests & minor improvement
  docs/source/plugin.rst
  docs/source/plugin/test.rst
  docs/source/tests.rst
  sopel/tests/mocks.py
  test/tests/test_tests_mocks.py
Labels: Documentation, Tweak

#2069 pronouns: add 2-word pronouns aliases
  sopel/modules/pronouns.py
Labels: Feature

#2072 Substitute Libera Chat for all public-facing references to freenode
  .github/ISSUE_TEMPLATE/config.yml
  NEWS
  README.rst
  contrib/sopel.cfg
  docs/source/cli.rst
  docs/source/configuration.rst
  sopel/config/__init__.py
  sopel/config/core_section.py
  sopel/modules/find_updates.py
  sopel/trigger.py
Labels: Documentation

#2071 loader: use `inspect` to make callable docs consistent
  sopel/loader.py
Labels: Tweak

#2074 currency: switch default to exchangerate.host; remove ratesapi.io
  sopel/modules/currency.py
  test/vcr/modules/currency/test_example_exchange_cmd_0.yaml
Labels: Tweak

#2076 tld: ccTLD data moved to its own wiki page
  sopel/modules/tld.py
Labels: Bugfix

#2073 build: remove EOL Python versions from Travis config
  .travis.yml
Labels: Build, High Priority

#2075 ci: switch to GitHub Actions
  .github/workflows/ci.yml
  .github/workflows/pypi.yml
  .travis.yml
  Makefile
  README.rst
Labels: Build, High Priority

#2078 gha: only run jobs when events are for 'sopel-irc' owned repos
  .github/workflows/ci.yml
Labels: Build

#2077 tld: fix `.tldcache clear` command breaking `.tld` until manual update
  sopel/modules/tld.py
Labels: Bugfix
