Repository sopel-irc/sopel, pull requests merged in 2021-09, with the labels that each got.

#2176 reddit: handle post and comment links in one regex
  sopel/modules/reddit.py
Labels: Bugfix

#2089 coretasks: activate `message-tags` and use it to ignore other bots' tagged messages
  sopel/coretasks.py
  sopel/plugins/rules.py
  test/plugins/test_plugins_rules.py
Labels: Feature, Low Priority, Documentation

#2138 sopel: use python3 style class and abc.ABC
  sopel/bot.py
  sopel/config/__init__.py
  sopel/config/types.py
  sopel/db.py
  sopel/irc/abstract_backends.py
  sopel/irc/isupport.py
  sopel/irc/utils.py
  sopel/logger.py
  sopel/modules/admin.py
  sopel/modules/currency.py
  sopel/modules/remind.py
  sopel/plugin.py
  sopel/plugins/exceptions.py
  sopel/plugins/handlers.py
  sopel/plugins/jobs.py
  sopel/plugins/rules.py
  sopel/tests/factories.py
  sopel/tests/mocks.py
  sopel/tools/__init__.py
  sopel/tools/jobs.py
  sopel/tools/target.py
  sopel/trigger.py
  test/irc/test_irc_abstract_backends.py
Labels: Tweak, Housekeeping

#2147 irc.utils: remove deprecated `CapReq.module` property
  sopel/irc/utils.py
Labels: Low Priority, Breaking Change, Housekeeping

#2148 cli.utils: remove deprecated `redirect_outputs()` function
  sopel/cli/utils.py
Labels: Low Priority, Breaking Change, Housekeeping

#2150 bot: remove deprecated methods for 8.0
  sopel/bot.py
Labels: Low Priority, Breaking Change, Housekeeping

#2170 module: import-time deprecation warning
  sopel/bot.py
  sopel/module.py
Labels: Tweak

#2177 docs: remove `test_tools` from "Testing tools" page
  docs/source/tests.rst
Labels: Low Priority, Documentation
