Repository sopel-irc/sopel, pull requests merged in 2021-12, with the labels that each got.

#2215 coretasks: alert owner if nick in `RPL_WELCOME` does not match config
  sopel/coretasks.py
Labels: Tweak

#2213 plugins: execute TODO that was waiting for end of py2 support
  sopel/plugins/__init__.py
Labels: Housekeeping

#2216 reddit, test: even more of the comments link format is optional
  sopel/modules/reddit.py
  test/modules/test_modules_reddit.py
Labels: Tweak

#2209 reddit: add flair text to link/submission output
  sopel/modules/reddit.py
Labels: Feature

#2222 adminchannel: fix, simplify, and comment hostmask utility function
  sopel/modules/adminchannel.py
  test/modules/test_modules_adminchannel.py
Labels: Bugfix, Housekeeping

#2214 wiktionary: allow for multi-line etymologies
  sopel/modules/wiktionary.py
Labels: Bugfix

#2199 bot: add plugins property
  sopel/bot.py
Labels: Feature

#2205 tools, tools.web: rework `web.decode()` to use modern stdlib
  docs/source/api.rst
  sopel/tools/__init__.py
  sopel/tools/web.py
Labels: Housekeeping

#2118 cli: remove legacy mode for run script
  sopel/cli/run.py
  test/cli/test_cli_run.py
Labels: Tweak, Bugfix, Breaking Change

#2133 Expose plugin versions, enable retrieval with `.version`
  sopel/modules/version.py
  sopel/plugins/handlers.py
Labels: Feature

#2179 sopel: reduce and reorganize imports for critical modules
  docs/source/plugin.rst
  docs/source/plugin/anatomy.rst
  docs/source/plugin/bot.rst
  docs/source/plugin/privileges.rst
  sopel/bot.py
  sopel/coretasks.py
  sopel/irc/backends.py
  sopel/plugin.py
  sopel/privileges.py
  sopel/tools/target.py
Labels: Tweak, Documentation

#2169 docs: about time for plugins
  docs/source/plugin/bot.rst
Labels: Documentation

#2185 sopel: type hint and basic setup
  Makefile
  dev-requirements.txt
  requirements.txt
  setup.cfg
  sopel/bot.py
  sopel/modules/bugzilla.py
  sopel/modules/currency.py
  sopel/modules/meetbot.py
  sopel/modules/reddit.py
  sopel/modules/remind.py
  sopel/modules/search.py
  sopel/modules/url.py
  sopel/plugin.py
  sopel/plugins/__init__.py
Labels: Low Priority, Tweak

#2224 db: add `forget_channel()` and `forget_plugin()` methods
  sopel/db.py
  test/test_db.py
Labels: Feature

#2225 wikipedia: refine no-consume logic for section hatnotes
  sopel/modules/wikipedia.py
Labels: Bugfix

#2220 plugins.rules: fix conflicting attributes in base classes
  docs/source/plugin/internals.rst
  sopel/plugins/rules.py
Labels: Low Priority, Housekeeping

#2228 tools: deprecate more Python 2-like shims
  docs/source/api.rst
  sopel/tools/__init__.py
Labels: Housekeeping
