Repository sopel-irc/sopel, pull requests merged in 2021-08, with the labels that each got.

#2134 irc: MyInfo namedtuple with proper type hint
  sopel/irc/utils.py
Labels: Low Priority, Tweak

#2135 cli.plugins: keep plugin meta info on loading error
  sopel/cli/plugins.py
Labels: Bugfix

#2172 requirements: pin requests on py3.3 to fix install/build
  requirements.txt
Labels: Bugfix, Build, High Priority

#2159 wikipedia: skip messagebox template contents
  sopel/modules/wikipedia.py
Labels: Bugfix

#2160 translate: handle failure/error better in `.mangle`
  sopel/modules/translate.py
Labels: Bugfix

#2162 tell: do not lstrip leading formatting
  sopel/modules/tell.py
  test/modules/test_modules_tell.py
Labels: Medium Priority, Bugfix

#2163 reddit: don't anchor to end of post links
  sopel/modules/reddit.py
Labels: Bugfix

#2164 config.types: silence `parse==bool` warning until 8.0
  sopel/config/types.py
Labels: Tweak

#2166 announce: make `_chunks()` helper safe against more input types
  sopel/modules/announce.py
  test/modules/test_modules_announce.py
Labels: Bugfix

#2168 wikipedia: handle transcluded sections better
  sopel/modules/wikipedia.py
Labels: Bugfix

#2171 reddit: stop PRAW checking for updates
  sopel/modules/reddit.py
Labels: Tweak

#2136 irc: add safe_text_length and use abc.ABC for AbstractBot
  sopel/bot.py
  sopel/irc/__init__.py
  test/test_irc.py
Labels: Tweak, Breaking Change

#2139 sopel: nuke sopel.test_tools
  sopel/test_tools.py
Labels: Tweak, Breaking Change

#2141 tools: follow through on all `removed_in='8.0'` deprecations
  sopel/tools/__init__.py
  test/test_tools.py
Labels: Low Priority, Tests, Breaking Change, Housekeeping

#2142 wikipedia: remove deprecated `lang_per_channel` config setting
  sopel/modules/wikipedia.py
Labels: Low Priority, Breaking Change, Housekeeping

#2144 loader: remove deprecated `trim_docstring()` function
  sopel/loader.py
Labels: Low Priority, Breaking Change, Housekeeping
