Repository sopel-irc/sopel, pull requests merged in 2021-04, with the labels that each got.

#2035 modules: add missing help messages
  sopel/modules/currency.py
  sopel/modules/meetbot.py
  sopel/modules/pronouns.py
  sopel/modules/wikipedia.py
Labels: Tweak

#2049 bot: deprecate (un)register_url_callback() functions
  sopel/bot.py
Labels: Documentation, Medium Priority, Tweak

#2044 config.types, test: add `BooleanAttribute` setting type
  sopel/config/types.py
  test/config/test_config_types.py
Labels: Feature

#2048 irc.isupport, announce: fix unexpected error (get) from .announce
  sopel/irc/isupport.py
  sopel/modules/announce.py
  test/irc/test_irc_isupport.py
Labels: Bugfix, Feature, Medium Priority

#2037 plugins: rule_lazy, find_lazy, and search_lazy
  docs/source/plugin/anatomy.rst
  sopel/bot.py
  sopel/loader.py
  sopel/plugin.py
  sopel/plugins/rules.py
  test/plugins/test_plugins_rules.py
  test/test_bot.py
  test/test_loader.py
  test/test_plugin.py
Labels: Feature

#2041 irc: timeout and logs
  docs/source/configuration.rst
  sopel/bot.py
  sopel/config/core_section.py
  sopel/coretasks.py
  sopel/irc/__init__.py
  sopel/irc/backends.py
Labels: High Priority, Tweak

#2047 cli: various user-friendly error messages
  sopel/cli/config.py
  sopel/cli/plugins.py
Labels: Low Priority, Tweak

#2050 irc: more ways for `bot.say()` to help with overlength messages
  sopel/bot.py
  sopel/irc/__init__.py
  sopel/modules/reddit.py
  sopel/modules/tld.py
  sopel/modules/wikipedia.py
  sopel/modules/wiktionary.py
  test/test_irc.py
Labels: Feature

#2052 find_updates: return in ALL the appropriate failure cases
  sopel/modules/find_updates.py
Labels: Bugfix
