Repository sopel-irc/sopel, pull requests merged in 2022-05, with the labels that each got.

#2265 seen: modify/fix stored value & delta calculation for Aware `trigger.time`
  sopel/modules/seen.py
Labels: Bugfix

#2270 events: rename and extend invite-related numerics
  sopel/tools/_events.py
Labels: Breaking Change

#2130 pronouns: fetch list from the pronoun.is GitHub repo at start
  sopel/modules/pronouns.py
Labels: Feature, Low Priority

#2272 rules: drop `draft/bot` tag
  sopel/plugins/rules.py
  test/plugins/test_plugins_rules.py
Labels: Tweak

#2257 docs: split files into subfolders
  docs/source/api.rst
  docs/source/config.rst
  docs/source/irc.rst
  docs/source/package.rst
  docs/source/package/bot.rst
  docs/source/package/config.rst
  docs/source/package/config/core_section.rst
  docs/source/package/config/types.rst
  docs/source/package/db.rst
  docs/source/package/formatting.rst
  docs/source/package/irc.rst
  docs/source/package/irc/backends.rst
  docs/source/package/irc/isupport.rst
  docs/source/package/irc/modes.rst
  docs/source/package/irc/utils.rst
  docs/source/package/lifecycle.rst
  docs/source/package/loader.rst
  docs/source/package/logger.rst
  docs/source/package/plugins.rst
  docs/source/package/plugins/exceptions.rst
  docs/source/package/plugins/handlers.rst
  docs/source/package/plugins/jobs.rst
  docs/source/package/plugins/plugins.rst
  docs/source/package/plugins/rules.rst
  docs/source/package/tools.rst
  docs/source/package/tools/calculation.rst
  docs/source/package/tools/events.rst
  docs/source/package/tools/identifiers.rst
  docs/source/package/tools/jobs.rst
  docs/source/package/tools/memories.rst
  docs/source/package/tools/target.rst
  docs/source/package/tools/time.rst
  docs/source/package/tools/web.rst
  docs/source/package/trigger.rst
  docs/source/plugin.rst
  docs/source/tests.rst
  docs/source/tests/factories.rst
  docs/source/tests/mocks.rst
  docs/source/tests/pytest.rst
  docs/source/trigger.rst
  sopel/trigger.py
Labels: Documentation, Housekeeping

#2256 bot, irc: IRC backend using asyncio
  sopel/bot.py
  sopel/cli/run.py
  sopel/irc/__init__.py
  sopel/irc/abstract_backends.py
  sopel/irc/backends.py
  sopel/irc/utils.py
  sopel/logger.py
  sopel/tests/mocks.py
Labels: Core/Networking

#2275 docs: use `sphinx-rfcsection` plugin (and fix some typos)
  dev-requirements.txt
  docs/source/conf.py
  sopel/irc/abstract_backends.py
  sopel/tools/identifiers.py
Labels: Tweak, Documentation

#2280 url: remove traceback from debug log when fetching URL fails
  sopel/modules/url.py
Labels: Tweak

#2278 config: don't manually hunt for CA paths
  sopel/config/core_section.py
Labels: Housekeeping, Core/Networking

#2286 Add workaround for excessive whitespace in MediaWiki excerpts (fixes #2259)
  sopel/modules/wikipedia.py
Labels: Low Priority, Bugfix
