Repository sopel-irc/sopel, pull requests merged in 2022-01, with the labels that each got.

#2235 isup: catch up errors from get site and from requests differently
  requirements.txt
  sopel/modules/isup.py
  test/modules/test_modules_isup.py
Labels: Tweak, Bugfix

#2233 tools.target: use slots for Channel and User types
  sopel/tools/target.py
Labels: Tweak

#2234 db, test: do not create nick ID by default
  sopel/db.py
  test/test_db.py
Labels: Tweak, Breaking Change

#2231 irc: implement CASEMAPPING parameter for ISUPPORT
  docs/source/api.rst
  docs/source/plugin/bot.rst
  sopel/bot.py
  sopel/config/core_section.py
  sopel/coretasks.py
  sopel/db.py
  sopel/irc/__init__.py
  sopel/modules/adminchannel.py
  sopel/modules/clock.py
  sopel/modules/find.py
  sopel/modules/invite.py
  sopel/modules/meetbot.py
  sopel/modules/seen.py
  sopel/modules/tell.py
  sopel/modules/translate.py
  sopel/modules/url.py
  sopel/tests/factories.py
  sopel/tools/__init__.py
  sopel/tools/identifiers.py
  sopel/tools/target.py
  sopel/tools/time.py
  sopel/trigger.py
  test/test_coretasks.py
  test/test_db.py
  test/tools/test_tools_identifiers.py
Labels: Feature, Breaking Change, Core/IRC Protocol Handling

#2238 rules: fix sphinx auto-doc warning and mypy error
  docs/source/plugin/internals.rst
  sopel/plugins/handlers.py
Labels: Documentation, Bugfix

#2239 db, docs: update intersphinx & fix some references
  docs/source/conf.py
  sopel/db.py
Labels: Low Priority, Tweak, Documentation

#2236 irc: implement CHANTYPES parameter for ISUPPORT
  sopel/coretasks.py
  sopel/irc/__init__.py
  sopel/tools/identifiers.py
  test/test_coretasks.py
  test/tools/test_tools_identifiers.py
Labels: Core/IRC Protocol Handling

#2240 adminchannel, coretasks: improve handling of bot's current nick
  sopel/coretasks.py
  sopel/modules/adminchannel.py
Labels: Medium Priority, Tweak, Core/IRC Protocol Handling
