Repository sopel-irc/sopel, pull requests merged in 2022-02, with the labels that each got.

#2244 loader, plugin, plugins.rules: add `allow_bots` decorator
  docs/source/plugin/anatomy.rst
  sopel/loader.py
  sopel/plugin.py
  sopel/plugins/rules.py
  test/plugins/test_plugins_rules.py
  test/test_plugin.py
Labels: Feature

#2242 translate: update `langcode()` helper to support Chinese
  sopel/modules/translate.py
Labels: Bugfix

#2245 reddit: handle image preview links
  sopel/modules/reddit.py
Labels: Feature, Low Priority

#2247 xkcd: account for Bing search returning mobile URLs
  sopel/modules/xkcd.py
Labels: Bugfix

#2249 url: bring additional sanity and calm to log output
  sopel/modules/url.py
Labels: Tweak

#2250 logger: convert newlines to spaces in IRC logging handler
  sopel/logger.py
Labels: Tweak

#2251 irc: fix some typos & formatting in docstrings
  sopel/irc/__init__.py
Labels: Documentation

#2254 search: consistently warn about excessive "site:" operators if no results
  sopel/modules/search.py
Labels: Tweak

#2218 url: bump user-agent
  sopel/modules/url.py
Labels: Tweak

#2226 docs: split bot documentation into separate files with minor fix
  docs/source/plugin.rst
  docs/source/plugin/bot.rst
  docs/source/plugin/bot/channels.rst
  docs/source/plugin/bot/style.rst
  docs/source/plugin/bot/talk.rst
  docs/source/plugin/test.rst
  docs/source/plugin/time.rst
Labels: Documentation, Housekeeping

#2232 sopel: move deprecated() to sopel.lifecycle
  docs/source/lifecycle.rst
  docs/source/package.rst
  sopel/bot.py
  sopel/config/types.py
  sopel/db.py
  sopel/lifecycle.py
  sopel/logger.py
  sopel/module.py
  sopel/tools/__init__.py
  sopel/tools/web.py
Labels: High Priority, Tweak

#2237 tools: move memory classes to tools.memories
  docs/source/api.rst
  sopel/bot.py
  sopel/tools/__init__.py
  sopel/tools/memories.py
  sopel/tools/target.py
  test/test_tools.py
  test/tools/test_tools_memories.py
Labels: Tweak

#2252 config: deprecate using a comma instead of a newline in ListAttribute
  sopel/config/types.py
Labels: Low Priority, Housekeeping
