Repository sopel-irc/sopel, pull requests merged in 2022-08, with the labels that each got.

#2320 irc: configure anti-looping system
  docs/source/configuration.rst
  sopel/config/core_section.py
  sopel/irc/__init__.py
  test/test_irc.py
Labels: Feature

#2327 irc: use deque for "stack" of recent messages
  sopel/irc/__init__.py
Labels: Tweak

#2330 currency: fiat_provider config option takes precedence
  sopel/modules/currency.py
Labels: Breaking Change, Housekeeping

#2329 loader, plugin: remove deprecated features
  sopel/loader.py
  sopel/plugin.py
  sopel/plugins/rules.py
  test/plugins/test_plugins_rules.py
Labels: Breaking Change, Housekeeping

#2328 ci, packaging, meta: modernize Python packaging for Sopel
  .github/workflows/ci.yml
  .github/workflows/pypi.yml
  CONTRIBUTING.md
  MANIFEST.in
  conftest.py
  contrib/githooks/main-hook.sh
  pyproject.toml
  pytest_run.py
  requirements.txt
  setup.cfg
  setup.py
  sopel.py
Labels: Build, Housekeeping

#2334 reqs: allow xmltodict 0.13
  pyproject.toml
Labels: Build

#2342 ci, plugins: Python 3.10 and other improvements
  .github/workflows/ci.yml
  dev-requirements.txt
  pyproject.toml
  setup.cfg
  sopel/plugins/__init__.py
Labels: Build, Housekeeping

#2332 help: replace with dependency on `sopel-help`
  pyproject.toml
  sopel/modules/help.py
Labels: Breaking Change, Housekeeping

#2344 coretasks: `.blocks hostmask` -> `.blocks host`
  sopel/coretasks.py
Labels: Documentation, Breaking Change, Housekeeping

#2345 coretasks: fix/improve `.blocks` help output
  sopel/coretasks.py
Labels: Tweak, Documentation
