Repository sopel-irc/sopel, pull requests merged in 2022-10, with the labels that each got.

#2351 remind: skip `remind_monitoring()` if IRC connection not ready
  sopel/modules/remind.py
Labels: Bugfix

#2354 bot: report exception type for relevant errors
  sopel/bot.py
Labels: Tweak

#2359 trigger: Make `sender` property more consistent
  docs/source/package/trigger.rst
  sopel/trigger.py
  test/test_trigger.py
Labels: Bugfix, Breaking Change, Core/IRC Protocol Handling

#2360 trigger: make `text` empty if `args` is empty, per docs
  sopel/trigger.py
  test/test_trigger.py
Labels: Bugfix, Breaking Change, Core/IRC Protocol Handling

#2364 Replace dev-requirements.txt with a [dev] extra
  .github/workflows/ci.yml
  CONTRIBUTING.md
  dev-requirements.txt
  pyproject.toml
Labels: Housekeeping

#2365 backends: try only utf8 when UTF8ONLY
  sopel/irc/abstract_backends.py
  test/irc/test_irc_abstract_backends.py
Labels: Core/IRC Protocol Handling

#2367 build: pin setuptools while we figure out PEP-0660 editable install
  pyproject.toml
Labels: Build
