Repository sopel-irc/sopel, pull requests merged in 2022-11, with the labels that each got.

#2369 backends: fix event loop close on invalid utf8 rx
  sopel/coretasks.py
  sopel/irc/abstract_backends.py
  test/irc/test_irc_abstract_backends.py
  test/test_coretasks.py
Labels: High Priority, Bugfix, Core/IRC Protocol Handling

#2361 unicode_info: ignore type check on unicodedata2
  sopel/modules/unicode_info.py
Labels: Tests, Housekeeping

#2366 formatting: fix `color('some text', 0)`
  sopel/formatting.py
  test/test_formatting.py
Labels: Medium Priority, Bugfix

#2372 backends: simplify UTF8ONLY handling
  sopel/coretasks.py
  sopel/irc/abstract_backends.py
  test/irc/test_irc_abstract_backends.py
  test/test_coretasks.py
Labels: Housekeeping
