Repository sopel-irc/sopel, pull requests merged in 2022-07, with the labels that each got.

#2243 db: adapt SopelDB to SQLAlchemy 2.x new style
  sopel/db.py
  test/test_db.py
Labels: Tweak

#2319 pip: allow praw from v4 to v7
  requirements.txt
Labels: Housekeeping

#2290 bot, loader, plugin, rules: add NOTICE message to rate limits
  docs/source/plugin/anatomy.rst
  sopel/bot.py
  sopel/loader.py
  sopel/plugin.py
  sopel/plugins/rules.py
  test/plugins/test_plugins_rules.py
  test/test_bot.py
  test/test_loader.py
  test/test_module.py
  test/test_plugin.py
Labels: Feature

#2300 implement flake8-type-checking
  dev-requirements.txt
  setup.cfg
  sopel/bot.py
  sopel/irc/__init__.py
  sopel/irc/modes.py
  sopel/modules/url.py
  sopel/plugin.py
  sopel/plugins/rules.py
  sopel/tools/target.py
  sopel/trigger.py
Labels: Housekeeping

#2313 plugins.handlers: override get_version() for EntryPointPlugin
  sopel/plugins/handlers.py
Labels: Feature

#2323 docs: improve coverage of `flood_max_wait` setting
  docs/source/configuration.rst
  sopel/config/core_section.py
Labels: Documentation

#2315 wikipedia: use say() instead of reply() when reporting a URL error
  sopel/modules/wikipedia.py
Labels: Tweak

#2321 coretasks: join channels on MOTD
  sopel/coretasks.py
Labels: Bugfix, Core/IRC Protocol Handling

#2335 db: fix typing.cast according to flake8-type-checking
  sopel/db.py
Labels: High Priority, Bugfix, Housekeeping
