Repository sopel-irc/sopel, pull requests merged in 2022-09, with the labels that each got.

#2346 irc: `LINELEN` ISUPPORT token support/use
  sopel/irc/__init__.py
  sopel/irc/isupport.py
  test/test_irc.py
Labels: Core/IRC Protocol Handling

#2338 seen: catch database write errors
  sopel/modules/seen.py
Labels: Tweak

#2349 unicode_info: Use unicodedata2, if available
  sopel/modules/unicode_info.py
Labels: Feature
