Repository sopel-irc/sopel, pull requests merged in 2023-04, with the labels that each got.

#2439 currency: add `.currencies` command to list supported symbols
  sopel/modules/currency.py
Labels: Feature

#2442 bot: eliminate problematic xrefs from `SopelWrapper` docs
  sopel/bot.py
Labels: Low Priority, Tweak, Documentation

#2441 bot, trigger: use status prefix in SopelWrapper
  sopel/bot.py
  sopel/trigger.py
  test/test_bot.py
Labels: Bugfix
