Repository sopel-irc/sopel, pull requests merged in 2023-07, with the labels that each got.

#2478 remind: remove plugin reimplemented as external package w/better tests
  sopel/modules/remind.py
  test/modules/test_modules_remind.py
Labels: Breaking Change

#2477 meetbot: remove in favor of external package
  sopel/modules/meetbot.py
Labels: Breaking Change, Housekeeping

#2481 bugzilla: remove module extracted to separate package
  sopel/modules/bugzilla.py
Labels: Housekeeping

#2489 docs: add example of plugin re-use
  docs/source/plugin/advanced.rst
Labels: Documentation

#2491 tld: fix regressions from type-hint cleanup
  sopel/modules/tld.py
Labels: Medium Priority, Bugfix
