Repository sopel-irc/sopel, pull requests merged in 2023-12, with the labels that each got.

#2575 wikipedia: fix urlparse usage & handle Special: namespace
  sopel/builtins/wikipedia.py
Labels: Bugfix

#2580 plugin: `require_bot_privilege()` implies `require_chanmsg()`
  sopel/plugin.py
  test/test_plugin.py
Labels: Tweak, Breaking Change

#2569 plugin: add capability.__str__ for better logs
  sopel/plugin.py
  sopel/plugins/capabilities.py
  test/test_plugin.py
Labels: Tweak, Core/Plugin Handling

#2581 bot: properly deprecate `search_url_callbacks()` method
  sopel/bot.py
Labels: Housekeeping

#2584 tell: avoid errors produced by empty tellee
  sopel/builtins/tell.py
Labels: Bugfix
