Repository sopel-irc/sopel, pull requests merged in 2023-06, with the labels that each got.

#2444 reddit: extract to external package
  pyproject.toml
  sopel/modules/reddit.py
  test/modules/test_modules_reddit.py
Labels: Breaking Change

#2434 Add more placeholders to rate-limit messages, move template interpolation from `Rule` to `Sopel`
  sopel/bot.py
  sopel/plugin.py
  sopel/plugins/rules.py
  test/plugins/test_plugins_rules.py
  test/test_bot.py
Labels: Feature, Core/Plugin Handling

#2446 tools.time: tweaks & tests
  sopel/modules/remind.py
  sopel/tools/time.py
  test/tools/test_tools_time.py
Labels: Tests, Bugfix, Breaking Change, Housekeeping

#2453 translate: Make help more helpful about language :hints
  sopel/modules/translate.py
Labels: Documentation

#2458 test: cover obvious SASL PLAIN edge cases
  test/coretasks/test_coretasks_cap.py
  test/coretasks/test_coretasks_sasl.py
Labels: Tests, Core/IRC Protocol Handling

#2468 Replace uses of deprecated `datetime.utcnow()`
  docs/source/plugin/time.rst
  sopel/bot.py
  sopel/coretasks.py
  sopel/irc/__init__.py
  sopel/modules/remind.py
  sopel/modules/uptime.py
  sopel/plugins/rules.py
  sopel/tools/time.py
  sopel/trigger.py
  test/plugins/test_plugins_rules.py
  test/test_bot.py
Labels: Tweak, Documentation, Housekeeping

#2462 mypy: fix currently known type-checking errors
  sopel/bot.py
  sopel/irc/backends.py
  sopel/modules/url.py
  sopel/plugins/rules.py
Labels: Tweak, Tests, Documentation

#2470 remind: fix import streamlining gone haywire
  sopel/modules/remind.py
  test/modules/test_modules_remind.py
Labels: High Priority, Bugfix

#2472 safety, url: skip handling invalid links with empty hostnames
  sopel/modules/safety.py
  sopel/modules/url.py
Labels: Bugfix

#2473 bot: don't add duplicate timestamp into error log line
  sopel/bot.py
Labels: Low Priority, Tweak

#2480 mypy: use generic types instead of `typing` aliases where possible
  sopel/bot.py
  sopel/config/types.py
  sopel/coretasks.py
  sopel/db.py
  sopel/irc/__init__.py
  sopel/irc/backends.py
  sopel/irc/capabilities.py
  sopel/irc/isupport.py
  sopel/irc/modes.py
  sopel/loader.py
  sopel/modules/currency.py
  sopel/modules/meetbot.py
  sopel/modules/safety.py
  sopel/modules/tld.py
  sopel/modules/url.py
  sopel/plugin.py
  sopel/plugins/capabilities.py
  sopel/plugins/handlers.py
  sopel/plugins/rules.py
  sopel/tests/factories.py
  sopel/tools/target.py
  sopel/tools/time.py
  sopel/trigger.py
Labels: Housekeeping
