Repository sopel-irc/sopel, pull requests merged in 2023-05, with the labels that each got.

#2455 build: pin urllib3 to <2.0 for now
  pyproject.toml
Labels: Build

#2430 irc: Improve output for common connection errors
  sopel/irc/__init__.py
  sopel/irc/abstract_backends.py
  sopel/irc/backends.py
Labels: Tweak, Core/Networking

#2431 irc: properly manage exception of the run-forever loop
  sopel/irc/backends.py
Labels: Tweak, Bugfix, Core/Networking

#2447 find: fix flags in pipe-separated substitutions
  sopel/modules/find.py
Labels: Bugfix

#2448 core: better bot-mode handling
  docs/source/configuration.rst
  sopel/config/core_section.py
  sopel/coretasks.py
  sopel/tools/target.py
  test/test_coretasks.py
  test/tools/test_tools_target.py
Labels: Tweak, Core/IRC Protocol Handling
