Repository sopel-irc/sopel, pull requests merged in 2023-03, with the labels that each got.

#2299 cli: look harder for $PWD/cfg, don't automatically start wizard
  sopel/cli/run.py
  sopel/cli/utils.py
  test/cli/test_cli_run.py
  test/cli/test_cli_utils.py
Labels: Tweak, Bugfix, Breaking Change

#2416 reload: remove `.update` command
  sopel/modules/reload.py
Labels: Breaking Change, Housekeeping

#2417 reload: better document limitations of `.reload` command
  sopel/modules/reload.py
Labels: Tweak, Documentation

#2418 reddit: add `slash_info` toggle
  sopel/cli/utils.py
  sopel/modules/reddit.py
Labels: Feature

#2419 logging: disallow `DEBUG` channel logs & stop inheriting console log level
  docs/source/configuration.rst
  sopel/bot.py
  sopel/config/core_section.py
Labels: Bugfix, Breaking Change

#2420 safety: logging level tweaks
  sopel/modules/safety.py
Labels: Tweak

#2341 bot, coretasks, irc, plugin, plugins: new capability negotiation system
  docs/source/package/irc.rst
  docs/source/package/irc/capabilities.rst
  docs/source/package/plugins.rst
  docs/source/package/plugins/capabilities.rst
  docs/source/plugin/advanced.rst
  docs/source/plugin/decorators.rst
  sopel/bot.py
  sopel/coretasks.py
  sopel/irc/__init__.py
  sopel/irc/capabilities.py
  sopel/irc/utils.py
  sopel/plugin.py
  sopel/plugins/capabilities.py
  sopel/plugins/handlers.py
  test/coretasks/test_coretasks_cap.py
  test/coretasks/test_coretasks_sasl.py
  test/irc/test_irc_capabilities.py
  test/plugins/test_plugins_capabilities.py
  test/test_coretasks.py
  test/test_plugin.py
Labels: Feature, Breaking Change, Core/Plugin Handling, Core/IRC Protocol Handling

#2428 url: Wrap DNS resolution in try/except
  sopel/modules/url.py
Labels: Bugfix

#2429 irc: unescape hexadecimal sequences in ISUPPORT parameter values
  sopel/irc/isupport.py
  test/irc/test_irc_isupport.py
Labels: Core/IRC Protocol Handling

#2437 pronouns: pronoun.is has been dead for months; switch to our own backend
  sopel/modules/pronouns.py
Labels: Bugfix

#2433 url: fix premature loop termination, docstring cleanup & slight refactoring
  sopel/modules/url.py
Labels: Documentation, Bugfix, Housekeeping

#2438 pronouns: make base URL of links configurable
  sopel/modules/pronouns.py
Labels: Feature
