Repository sopel-irc/sopel, pull requests merged in 2023-10, with the labels that each got.

#2518 README: fix link to *latest source* archive
  README.rst
Labels: Documentation

#2514 tools.memories: remove obsolete LGTM tricks
  sopel/tools/memories.py
Labels: Housekeeping

#2520 contrib: drop Python 3.7 from tox config
  contrib/tox.ini
Labels: Housekeeping

#2521 bot: add deprecation notice to SopelWrapper
  sopel/bot.py
Labels: Long-term Planning, Housekeeping

#2522 lifecycle: issue deprecation notices in pre-releases
  sopel/lifecycle.py
Labels: Low Priority, Housekeeping

#2496 docs, dev-requirements: upgrade sphinx and try to fix some type issues with documentation
  dev-requirements.txt
  docs/source/conf.py
  docs/source/index.rst
  docs/source/package/plugins/rules.rst
  docs/source/plugin/advanced.rst
  sopel/db.py
  sopel/plugin.py
  sopel/plugins/rules.py
  sopel/tools/identifiers.py
  sopel/tools/memories.py
  sopel/tools/target.py
  sopel/trigger.py
Labels: Documentation

#2528 CodeQL: only scan `sopel` directory
  .github/workflows/codeql.yml
Labels: Build, Housekeeping

#2534 CodeQL: restrict paths on which action should run
  .github/workflows/codeql.yml
Labels: Build, Housekeeping

#2535 Pin `packaging` version
  pyproject.toml
Labels: Tweak

#2495 docs: basic tutorials
  docs/source/plugin.rst
  docs/source/plugin/tutorials.rst
  docs/source/plugin/tutorials/configuration-and-setup.rst
  docs/source/plugin/tutorials/first-plugin.rst
  docs/source/plugin/tutorials/playing-with-commands.rst
Labels: Documentation

#2519 build, test: upgrade to vcrpy>=5 & refresh broken cassettes
  dev-requirements.txt
  pyproject.toml
  test/vcr/modules/search/test_example_duck_0.yaml
  test/vcr/modules/search/test_example_duck_1.yaml
  test/vcr/modules/search/test_example_suggest_0.yaml
  test/vcr/modules/search/test_example_suggest_1.yaml
  test/vcr/modules/search/test_example_suggest_2.yaml
  test/vcr/modules/url/test_example_title_command_0.yaml
Labels: Tests, Build, hacktoberfest-accepted, Housekeeping

#2504 modules: rename built-in plugins to "builtins"
  docs/source/plugin/advanced.rst
  sopel/builtins/__init__.py
  sopel/builtins/admin.py
  sopel/builtins/adminchannel.py
  sopel/builtins/announce.py
  sopel/builtins/calc.py
  sopel/builtins/choose.py
  sopel/builtins/clock.py
  sopel/builtins/countdown.py
  sopel/builtins/currency.py
  sopel/builtins/dice.py
  sopel/builtins/emoticons.py
  sopel/builtins/find.py
  sopel/builtins/find_updates.py
  sopel/builtins/help.py
  sopel/builtins/invite.py
  sopel/builtins/isup.py
  sopel/builtins/lmgtfy.py
  sopel/builtins/ping.py
  sopel/builtins/pronouns.py
  sopel/builtins/rand.py
  sopel/builtins/reload.py
  sopel/builtins/safety.py
  sopel/builtins/search.py
  sopel/builtins/seen.py
  sopel/builtins/tell.py
  sopel/builtins/tld.py
  sopel/builtins/translate.py
  sopel/builtins/unicode_info.py
  sopel/builtins/units.py
  sopel/builtins/uptime.py
  sopel/builtins/url.py
  sopel/builtins/version.py
  sopel/builtins/wikipedia.py
  sopel/builtins/wiktionary.py
  sopel/builtins/xkcd.py
  sopel/plugins/__init__.py
  sopel/plugins/handlers.py
  test/builtins/test_builtins_adminchannel.py
  test/builtins/test_builtins_announce.py
  test/builtins/test_builtins_choose.py
  test/builtins/test_builtins_find_updates.py
  test/builtins/test_builtins_isup.py
  test/builtins/test_builtins_tell.py
  test/builtins/test_builtins_url.py
  test/test_bot.py
  test/vcr/builtins/currency/test_example_exchange_cmd_0.yaml
  test/vcr/builtins/currency/test_example_exchange_cmd_1.yaml
  test/vcr/builtins/search/test_example_duck_0.yaml
  test/vcr/builtins/search/test_example_duck_1.yaml
  test/vcr/builtins/search/test_example_suggest_0.yaml
  test/vcr/builtins/search/test_example_suggest_1.yaml
  test/vcr/builtins/search/test_example_suggest_2.yaml
  test/vcr/builtins/translate/test_example_tr2_0.yaml
  test/vcr/builtins/translate/test_example_tr2_1.yaml
  test/vcr/builtins/translate/test_example_tr2_2.yaml
  test/vcr/builtins/url/test_example_title_command_0.yaml
Labels: Housekeeping

#2516 Add Python 3.12 support
  .github/workflows/ci.yml
  Makefile
  contrib/tox.ini
  dev-requirements.txt
  docs/source/plugin/test.rst
  pyproject.toml
  sopel/tests/mocks.py
Labels: Medium Priority, Build, Housekeeping

#2536 contrib: add tox data directory to gitignore
  contrib/.gitignore
Labels: Housekeeping
