Repository sopel-irc/sopel, pull requests merged in 2023-11, with the labels that each got.

#2531 config: space before zone in `default_time_format`'s default
  sopel/config/core_section.py
Labels: Tweak

#2530 calc: improve help output, test coverage (now 100%)
  sopel/builtins/calc.py
Labels: Tests

#2532 dice: bugfixes, type hints, and additional tests
  sopel/builtins/dice.py
Labels: Tests, Bugfix, Housekeeping

#2543 tools, tools.calculation: docs/type-hint improvements, API fixes, better test coverage
  docs/source/package/tools/calculation.rst
  sopel/tools/__init__.py
  sopel/tools/calculation.py
  test/tools/test_tools_calculation.py
Labels: Documentation, Bugfix, Housekeeping

#2545 plugins: avoid crash on broken symlink
  sopel/plugins/__init__.py
  test/test_plugins.py
Labels: Bugfix, Core/Plugin Handling

#2546 test: explicitly specify `testpaths`
  Makefile
  pyproject.toml
Labels: Tweak, Bugfix

#2525 memories: test/fix interactions between `SopelIdentifierMemory` ↔ `dict`
  sopel/tools/memories.py
  test/tools/test_tools_memories.py
Labels: Medium Priority, Bugfix, hacktoberfest-accepted

#2539 plugin: clean up redundant in-docstring parameter type annotations
  sopel/plugin.py
Labels: Documentation

#2540 privileges, plugin, tools.target, docs: channel privileges as IntFlag
  docs/source/plugin/privileges.rst
  sopel/plugin.py
  sopel/privileges.py
  sopel/tools/target.py
Labels: Tweak

#2550 coretasks, docs: fix auto-saving `.blocks add host`; improve "Ignoring Users" docs & x-refs
  docs/source/conf.py
  docs/source/configuration.rst
  docs/source/plugin/anatomy.rst
  sopel/bot.py
  sopel/config/core_section.py
  sopel/coretasks.py
  sopel/plugin.py
Labels: Documentation, Bugfix

#2552 irc, bot, builtins: add & use `AbstractBot.make_identifier_memory()` helper
  sopel/bot.py
  sopel/builtins/find.py
  sopel/builtins/translate.py
  sopel/builtins/url.py
  sopel/irc/__init__.py
  test/test_coretasks.py
  test/test_irc.py
Labels: Feature

#2555 plugin: type-hint `priority` argument as `Literal[]`
  sopel/plugin.py
Labels: Tweak

#2558 docs: set `maxdepth` or `titlesonly` on overly-long TOCs
  docs/source/conf.py
  docs/source/configuration.rst
  docs/source/index.rst
  docs/source/package/config.rst
  docs/source/package/config/core_section.rst
  docs/source/package/irc.rst
  docs/source/package/plugins.rst
  docs/source/package/tools.rst
  docs/source/tests.rst
  sopel/plugins/rules.py
  sopel/tools/__init__.py
  sopel/tools/memories.py
Labels: Documentation, Housekeeping

#2561 coretasks: fix SASL EXTERNAL without password set
  sopel/coretasks.py
  test/coretasks/test_coretasks_sasl.py
Labels: Bugfix

#2533 docs: install and running instance documentation
  contrib/README.md
  contrib/sopel.cfg
  contrib/sopel.conf
  contrib/sopel.service
  contrib/sopel@.service
  docs/source/faq.rst
  docs/source/index.rst
  docs/source/plugin/tutorials/configuration-and-setup.rst
  docs/source/run.rst
  docs/source/run/cli.rst
  docs/source/run/configuration.rst
  docs/source/run/install.rst
  docs/source/run/plugin.rst
  docs/source/run/service.rst
Labels: Documentation
