Repository sopel-irc/sopel, pull requests merged in 2023-02, with the labels that each got.

#2400 bot: don't let per-channel config skip coretasks handlers
  sopel/bot.py
Labels: Low Priority, Tweak

#2405 plugin: `require_privilege()` implies `require_chanmsg()`
  sopel/plugin.py
  test/test_module.py
Labels: Tweak, Breaking Change

#2406 irc: use `threading.Event` for internal `_connection_registered` flag
  sopel/bot.py
  sopel/coretasks.py
  sopel/irc/__init__.py
  test/test_coretasks.py
Labels: Tweak

#2409 docs: update sphinxcontrib-autoprogram
  dev-requirements.txt
Labels: Low Priority, Tweak, Documentation, Build

#2410 logger: use newer, more robust IRC connection check
  sopel/logger.py
Labels: Tweak

#2411 py, build: drop `py` plugin from core & require external package
  pyproject.toml
  sopel/modules/py.py
  test/vcr/modules/py/test_example_py_0.yaml
Labels: Breaking Change, Housekeeping

#2414 wikipedia: support query strings in Wikipedia URLs
  sopel/modules/wikipedia.py
Labels: Bugfix

#2368 abstract_backends: safe() all prepare_command args
  sopel/irc/__init__.py
  sopel/irc/abstract_backends.py
  test/irc/test_irc_abstract_backends.py
Labels: Bugfix

#2415 reqs: do not require sopel-py
  pyproject.toml
Labels: Breaking Change
