Repository sopel-irc/sopel, pull requests merged in 2023-01, with the labels that each got.

#2392 pyproject.toml: revert "dev" dependencies and requirements file
  .github/workflows/ci.yml
  CONTRIBUTING.md
  dev-requirements.txt
  pyproject.toml
Labels: Build

#2386 irc: annotate submodules with internal-use warnings
  sopel/irc/__init__.py
  sopel/irc/abstract_backends.py
  sopel/irc/backends.py
  sopel/irc/isupport.py
  sopel/irc/modes.py
  sopel/irc/utils.py
Labels: Documentation

#2388 wikipedia: support media fragments
  sopel/modules/wikipedia.py
Labels: Feature, Bugfix

#2370 trigger, irc: use STATUSMSG to handle status specific messages in channels
  sopel/irc/__init__.py
  sopel/tests/factories.py
  sopel/tests/pytest_plugin.py
  sopel/trigger.py
  test/test_trigger.py
Labels: Bugfix, Core/IRC Protocol Handling

#2371 config: strip quotes from FilenameAttribute
  sopel/config/types.py
  test/test_config.py
Labels: Bugfix

#2394 irc, backends: dummy non-connected backend for convenience
  sopel/irc/__init__.py
  sopel/irc/backends.py
Labels: Medium Priority, Documentation, Core/Networking

#2396 coretasks: send WHO to get realname for never-seen users on JOIN
  sopel/coretasks.py
Labels: Bugfix, Core/IRC Protocol Handling
