Repository sopel-irc/sopel, pull requests merged in 2024-10, with the labels that each got.

#2628 ci, contrib, dice, meta: enable testing on Python 3.13 + fix warnings
  .github/workflows/ci.yml
  contrib/tox.ini
  pyproject.toml
  sopel/builtins/dice.py
  sopel/builtins/url.py
Labels: Build, Housekeeping

#2624 config.types.ChoiceAttribute: log the invalid value if validation fails
  sopel/config/types.py
Labels: Tweak

#2285 url: improve private IP protection
  pyproject.toml
  sopel/builtins/url.py
  test/builtins/test_builtins_url.py
Labels: Bugfix, Security

#2577 meta: update bug report issue template with logs FAQ link
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: Housekeeping

#2589 find: support escaping backslash, fix double-bolding, and add basic tests
  sopel/builtins/find.py
  test/builtins/test_builtins_find.py
Labels: Tests, Bugfix

#2631 Pin `mypy` to 1.11.2
  dev-requirements.txt
Labels: High Priority, Build

#2616 mypy: add --disallow-incomplete-defs option
  Makefile
  sopel/bot.py
  sopel/builtins/calc.py
  sopel/builtins/dice.py
  sopel/builtins/safety.py
  sopel/builtins/units.py
  sopel/builtins/url.py
  sopel/coretasks.py
  sopel/db.py
  sopel/irc/__init__.py
  sopel/irc/backends.py
  sopel/irc/modes.py
  sopel/lifecycle.py
  sopel/plugins/handlers.py
  sopel/plugins/rules.py
  sopel/tools/calculation.py
  sopel/tools/identifiers.py
  sopel/tools/memories.py
Labels: Housekeeping

#2630 pytest_plugin: disable flood protection for example tests
  sopel/tests/pytest_plugin.py
Labels: Build, Bugfix, Housekeeping

#2633 plugins.handlers: fix some PyFilePlugin logic errors
  sopel/plugins/handlers.py
  test/plugins/test_plugins_handlers.py
Labels: Tweak, Bugfix

#2617 docs: add advanced tip about scheduling function calls
  docs/source/plugin/advanced.rst
  sopel/plugin.py
Labels: Low Priority, Documentation, Housekeeping

#2629 bot, rules: fix rate limiting rules without a rate limit
  sopel/bot.py
  sopel/plugins/rules.py
  test/plugins/test_plugins_rules.py
  test/test_bot.py
Labels: Bugfix

#2638 cli.plugins: include version number in `sopel-plugins show`
  sopel/cli/plugins.py
Labels: Low Priority, Tweak, Core/Plugin Handling
