Repository sopel-irc/sopel, pull requests merged in 2024-11, with the labels that each got.

#2594 Fix version check for entrypoint plugins with unequal project/package names
  sopel/plugins/handlers.py
  test/plugins/test_plugins_handlers.py
Labels: Bugfix

#2642 irc: `versionadded` notes + `Optional` annotation migration
  sopel/irc/__init__.py
Labels: Documentation, Housekeeping

#2645 Update master's version metadata
  pyproject.toml
Labels: Housekeeping
