Repository sopel-irc/sopel, pull requests merged in 2025-09, with the labels that each got.

#2586 version: retrieve commit hash for git worktrees
  sopel/builtins/version.py
Labels: Feature, Tweak

#2595 cli: add `sopel-config edit` subcommand
  sopel/cli/config.py
Labels: Feature, Low Priority

#2637 Support `invite-notify` CAP
  sopel/builtins/admin.py
  sopel/coretasks.py
  test/builtins/test_builtins_admin.py
  test/test_coretasks.py
Labels: Feature, Core/IRC Protocol Handling

#2706 url: remove built-in url plugin
  sopel/builtins/url.py
  test/builtins/test_builtins_url.py
Labels: Housekeeping
