Repository sopel-irc/sopel, pull requests merged in 2025-08, with the labels that each got.

#2693 Makefile: add cleanup recipes
  Makefile
Labels: Housekeeping

#2652 bot, plugin, plugin.rules: optionally include admins in rate limits too
  sopel/bot.py
  sopel/plugin.py
  sopel/plugins/rules.py
  test/plugins/test_plugins_rules.py
  test/test_bot.py
Labels: Feature

#2687 bot, coretasks, config: add `hostmask` block type
  sopel/bot.py
  sopel/config/core_section.py
  sopel/coretasks.py
  test/bot/test_bot_blocking.py
Labels: Feature

#2683 Move dev-requirements to pyproject.toml
  .github/workflows/ci.yml
  CONTRIBUTING.md
  contrib/tox.ini
  dev-requirements.txt
  pyproject.toml
Labels: Housekeeping

#2694 Move mypy options from Makefile to pyproject.toml
  Makefile
  pyproject.toml
Labels: Low Priority, Housekeeping

#2676 coretasks: handle '*' placeholder for omitted channel in WHO/WHOX RPLs
  sopel/coretasks.py
  test/test_coretasks.py
Labels: Bugfix
