Repository sopel-irc/sopel, pull requests merged in 2025-05, with the labels that each got.

#2636 bot, plugins: deprecate bot.{add|remove}_plugin
  sopel/bot.py
  sopel/plugins/handlers.py
Labels: Housekeeping, Core/Plugin Handling

#2673 tld: remove built-in plugin in favor of external package
  sopel/builtins/tld.py
Labels: Housekeeping

#2674 unicode_info: remove plugin in favor of external package
  sopel/builtins/unicode_info.py
Labels: Breaking Change, Housekeeping
